- CMakeLists.txt
- app/src/VersionInfoTemplate.cs
- app/src/swig/app.i
Like the C++ libraries, Unity libraries now have the option to declare
whether they were built from a Github Actions (in other words, whether
they're an official release) or whether they're custom built.
> Added user agent string for build source to unity builds.

- CMakeLists.txt
- editor/CMakeLists.txt
- editor/app/CMakeLists.txt
Add building `Firebase.Editor.dll` as part of Cmake build.
> Build Firebase.Editor.dll

- editor/CMakeLists.txt
Was disabled due to a bug in code.
Re-enable it after the patch is copied to Github
> Build Crashlytics editor tool

- .github/workflows/sdk_build.yml
- cmake/FindUnity.cmake
Note that it also builds for Mac and Windows, but both currently fail on different errors.
Also changes it to only require iOS if building for iOS, instead of checking for Apple.
> Add a workflow to build for Linux

- .github/workflows/integration_tests.yml
- scripts/gha/print_matrix_configuration.py
1. Using variable from config script instead of the input
2. Remove unsupported Unity version for now
***
> Using variable from config script instead of the input

- CMakeLists.txt
- cmake/FindUnity.cmake
- firestore/CMakeLists.txt
+ Linux mono wrapper script doesn't work for newer version of Unity (>2019), comment out for now
Unity modify the folder structure under MonoBleedingEdge folder, remove mono from bin and only leave xbuild there, which would fail the file size check during wrapping the env. The script only looked under /bin/ folder, but the actual working one is the msbuild under /lib/ folder
+ Firestore one file name failed the case sensitive check on linux
+ Only build editor on mac desktop
***
Local and GHA
***
***
> fix linux build

- cmake/android_dependencies.cmake
- crashlytics/CMakeLists.txt
Messaging has an additional dependency on iid, and Crashlytics was missing
Messaging depends on iid in Android, so add it to the set of dependencies.
Crashlytics was incorrectly using Auth, so added the Crashlytics dependencies.
***
Building for Android, and checking the resulting Dependencies.xml files
***
***
> Fix the Android dependencies for Crashlytics and Messaging

- .github/workflows/package.yml
- .github/workflows/update_versions.yml
- build_package.py
Make package script to update guids and create packages together
***
Local and GHA
***
***
> Make package script to update guids and create packages together

- CMakeLists.txt
- build_android.sh
- crashlytics/CMakeLists.txt
- crashlytics/src/cpp/CMakeLists.txt
Add the special logic needed to generate the Crashlytics proguard file. This is needed since Crashlytics does not exist in the C++ repo like the other products do.
***
Built for Android locally
***
***
> Add logic to generate the Crashlytics proguard file

- .github/workflows/integration_tests.yml
Close event trigger workflow incorrectly. PR is not merged, but the workflow didn't cancel itself as excepted.
https://github.com/firebase/firebase-unity-sdk/actions/runs/1861582366
Now workflow cancel itself correctly: 
https://github.com/firebase/firebase-unity-sdk/runs/5241454052?check_suite_focus=true
***
***
> Cancel unnecessary workflow run

- .github/workflows/integration_tests.yml
[Yesterday's fix](https://github.com/firebase/firebase-unity-sdk/pull/183) causes an error, because certain GitHub variable doesn't exist with non-PR trigger:
https://github.com/firebase/firebase-unity-sdk/runs/5252098713?check_suite_focus=true
Now using this statement to ensure it works: `"${{ github.event.pull_request.merged == true}}" == "true"`
***
PR closed but not merged - workflow canceled: https://github.com/firebase/firebase-unity-sdk/actions/runs/1866039558
Manual  trigger - workflow running: https://github.com/firebase/firebase-unity-sdk/actions/runs/1866043270
Label trigger - workflow running: https://github.com/firebase/firebase-unity-sdk/actions/runs/1866063380
***
***
> Fix cancel workflow run

- cmake/swig_fix.py
This fixes the "exception propagation" issue in Firestore, where C++ exceptions were not propagating up to C# exceptions.
Googlers can see b/220897535 for details.
> swig_fix.py: fix the ignore path for Firestore's exception checks

- firestore/testapp/Assets/Firebase/Sample/Firestore/UIHandlerAutomated.cs
`TestAuthIntegration` requires a specific Security Rules setup in the Firestore console. This PR adds a comment to document this requirement. Without this setup, the test will erroneously fail.
> Comment in TestAuthIntegration about the required security rules

- dynamic_links/testapp/Assets/Firebase/Sample/DynamicLinks/UIHandlerAutomated.cs
Dynamic Links uses Unity's Application.identifier under the hood to fill in some fields, but that results in an empty string on Windows and Linux. Since that is expected on desktop, change the tests to only check for that identifier on mobile and Apple platforms, which are expected to be present.
***
***
***
> Update the Dynamic Links testapp to handle Windows and Linux

- docs/readme.md
- editor/app/src/PythonExecutor.cs
Some users are still having problems with finding the python interpreter. One possible reason is that when checking just "python" it is prompting for user input and failing, so we will move that to the back of the list, so that it checks the most common case of "python3", which does not seem to have this problem, first.
***
***
***
https://github.com/firebase/firebase-unity-sdk/issues/154
> Move python to the back of the list of interpreters

- .github/workflows/sdk_build.yml
Firestore is having a problem with python, as it finds multiple versions. This can be worked around by setting FIREBASE_PYTHON_HOST_EXECUTABLE, so for now force that to be the version of python we are installing.
***
Ran this: https://github.com/firebase/firebase-unity-sdk/actions/runs/2210433023
***
***
> Force the windows workflow to use a specific python path

- cmake/build_shared.cmake
- cmake/build_universal.cmake
> reduce android sdk size by stripping the debug symbol

- cmake/build_shared.cmake
- cmake/firebase_swig.cmake
- firestore/CMakeLists.txt
The shared libraries have too many symbols, duplicating what is in app. Change it to link against the universal app library, which will keep the symbols in the shared libraries down.
***
***
***
> Make shared libraries link against the universal one

- CMakeLists.txt
The Linux Unity editor was crashing in the Firestore testapp. From what I can tell, the Unity editor was likely build with this option enabled, and mixing the library without it was the cause of the crash. So we will force the option to always be on for Linux builds. Note that standalone builds were not crashing, so it was likely just a problem with the Unity editor being built with that option.
***
***
***
> Force on the CXX11_ABI flag

- aar_builder/build_aar.py
- cmake/build_aar.cmake
- cmake/build_firebase_aar.cmake
- cmake/firebase_unity_version.cmake
- docs/readme.md
The Android srcaar files need to have unique package names in the AndroidManifest files within them, so that when they get merged together with a mainTemplate.gradle file, they can be resolved correctly.
***
***
***
https://github.com/firebase/quickstart-unity/issues/1264
> Fix issue with Android package name

- .github/workflows/sdk_build.yml
- docs/readme.md
- scripts/build_scripts/build_zips.py
Now that we are building on GHA, we can add support for Apple Silicon chips. This adds logic to the python script to build both x86_64 and arm64, and then merge them together with lipo.
***
Validating that the bundle files have both symbols, and running it locally on an M1 Mac.
***
***
https://github.com/firebase/firebase-unity-sdk/issues/278
> Add support for Apple M1 Silicon

- crashlytics/src/cpp/CMakeLists.txt
The new Crashlytics cocoapods uses a different structure than the rest of the Firebase pods, so we explicitly add the new path to the set of include directories.
***
Building iOS locally against the 9.0.0 Cocoapods
***
***
> Add an additional path for iOS Crashlytics headers

- .github/workflows/sdk_build.yml
The previous build system used boringssl for builds, and it is required now on Mac, so turn it on for the other desktop platforms.
***
***
***
> Turn on boringssl on linux and windows builds

- swig_post_process.py
Currently, it is observed in versions 8.10.0 onward that some functions (like public static EventCheckoutProgress) have the letter 'k' omitted. 
Updated the replace function to replace the first 'k'
Resolves #279
> Possible fix to PR 201 (Fix for swig post process for analytics properties)

- crashlytics/src/cpp/CMakeLists.txt
- docs/readme.md
Add missing { *; } to the Crashlytics proguard file, and add special logic for the FirebaseCrashlyticsNdk library, which is incorrectly not being kept when enabling proguard.
***
Tested locally by replacing the proguard file with the generated one.
***
***
https://github.com/firebase/quickstart-unity/issues/1268
> Fix Crashlytics proguard file generation

- cmake/unity_ios.cmake
- docs/readme.md
Set CMAKE_OSX_DEPLOYMENT_TARGET, which in turn sets the iOS minimum version flag. Note though that it seems a bit buggy when building fat libraries, as it gets confused on which minimum version flag to use. This will work on clean builds, which will be enough for a release, but for a long term fix we will likely need to change the build scripts to build device and simulator separately, and then merge them together afterwards.
***
Building locally, and running on an iOS simulator with iPhoneOS 12.4, and running on a device with iPhoneOS 13.3
***
***
https://github.com/firebase/firebase-unity-sdk/issues/294 …
> Set the iOS minimum version flag in the toolchain

- .github/workflows/sdk_build.yml
- cmake/firebase_unity_version.cmake
Add boringssl back for Linux, since it is needed for Firestore to function properly. Pin the C++ SDK to the special unity-v9.0.0 branch, which has the PIC fix on top of the previous 9.0.0 release
***
***
***
> Add boringssl back to Linux, with the fixed C++

- build_ios.sh
The CMAKE_OSX_SYSROOT needs to be empty to handle device and simulator together.
***
***
***
> Make build_ios pass empty sysroot when building device and simulator

- cmake/android_dependencies.cmake
- docs/readme.md
In the transition to GHA, Messaging lost the extra dependency on iid it needs, or else there is a problem when also using Functions with duplicated symbols.
***
***
***
https://github.com/firebase/quickstart-unity/issues/1274
> Fix messaging duplicate symbol bug

- unity_packer/exports.json
We bump up supported Unity version to `2018` for I/O build. This change will make sure all the manifest and GPRv2 are updated properly.
***
N/A
***
***
> Bump up Unity version after I/O 2022

- .github/workflows/integration_tests.yml
- scripts/gha/build_testapps.py
- scripts/gha/integration_testing/test_validation.py
- scripts/gha/print_matrix_configuration.py
- scripts/gha/unity_installer.py
`Playmode` added as a new platform.
***
See the comment below
***
***
> Add playmode (in editor mode) test in CI

- cmake/external/google_minijson.patch
- cmake/external/minijson.cmake
- docs/readme.md
In the previous build system, the MiniJson library was put into a Google namespace, to prevent overlapping with other usages. This adds that logic back in, by patching the file when it is downloaded.
***
Building locally
***
***
https://github.com/firebase/firebase-unity-sdk/issues/306
> Patch MiniJson with a google namespace

- database/src/DataSnapshot.cs
- database/src/DatabaseReference.cs
Database was using the normal namespace for MiniJSON, so it needs to be updated for the Google one.
***
***
***
> Fix MiniJSON namespace in Database

- firestore/scripts/cp_unity_testapp.py
In #220 the `cp_unity_testapp.py` script was added; however, I forgot to implement the part where the command-line flags were actually considered. This PR fixes the bug by adding the command-line flag handling logic.
> cp_unity_testapp.py: fix bug where command-line flags were ignored.

- analytics/testapp/Assets/Firebase/Sample/Analytics/UIHandler.cs
- docs/readme.md
Call InitiateOnDeviceConversionMeasurementWithEmailAddress in the analytics testapp
No actual code change is necessary since swig autogenerates this method.
The underlying C++ method is in the C++ SDK's 9.1.0 release.
***
Built from source and verified that the swig generated file defines the following:
public static void InitiateOnDeviceConversionMeasurementWithEmailAddress(string emailAddress)
Used this built version of the SDK in an analytics testapp and updated the testapp to call the new method
Verified that testapp tests still succeeded with no new errors.
***
***
> [Analytics] Add InitiateOnDeviceConversionMeasurementWithEmailAddress

- app/src/cpp_instance_manager.h
The internal GetInstance classes are sometimes expected to return null, for example Storage does if passing an invalid bucket.  Instead of checking for null in each case, it seems better to let the cpp_instance_manager handle when null is passed in, especially instead of storing those nulls, as it currently does, assuming assertions are off.
***
Building and running locally
***
***
> Handle passing null to cpp instance manager

- .github/workflows/android.yml
- .github/workflows/build_android.yml
- scripts/gha/print_matrix_configuration.py
The C++ repo recently changed the ndk version to 21e, so update the Unity repo to use the same.
***
https://github.com/firebase/firebase-unity-sdk/actions/runs/2466239666
***
***
> Update the ndk version to 21e

- editor/app/src/PythonExecutor.cs
Disables the error log when unable to find python on a windows machine.
This is done because for Windows devices, PythonExecutor uses an executable instead of python. So even if python is not found, the build should still succeed and there is no need to log an error. 
Resolves https://github.com/firebase/quickstart-unity/issues/1289
***
Not yet tested.
***
- [ x] Bug fix. Add the issue # below if applicable.
***
> Don't log an error about missing python on windows

- scripts/gha/unity_installer.py
`u3d` seems missing `u3d list` cmd on Windows platform. 
Removed this cmd.
***
Unity Installation now succeed on Windows runners: https://github.com/firebase/firebase-unity-sdk/actions/runs/2694648743
***
***
> [bugfix] build for windows consistently fails on windows Unity installation.

- .github/workflows/build_starter.yml
- .github/workflows/integration_tests.yml
- scripts/gha/unity_installer.py
1. cleaning un unity installation before retry unity installation
2. specify `u3d` version and disable `u3d` version check
3. remove flaky `u3d` cmd
4. set ruby version
5. add `playmode` test as default
6. If leave the `packaged_sdk_run_id` empty, then uses latest released Unity SDK
***
Unity installation passed:
Packaging workflow:
https://github.com/firebase/firebase-unity-sdk/actions/runs/2701251024
https://github.com/firebase/firebase-unity-sdk/actions/runs/2701049788
Integration Test workflow:
https://github.com/firebase/firebase-unity-sdk/actions/runs/2701391198
https://github.com/firebase/firebase-unity-sdk/actions/runs/2701387893
https://github.com/firebase/firebase-unity-sdk/actions/runs/2701386315
https://github.com/firebase/firebase-unity-sdk/actions/runs/2701434427 …
> De-flaky the unity installation in CI

- scripts/gha/build_testapps.py
The Firestore Android testapp was failing to build, because it requires minification. The root cause is that the GitHub runners have the android-33 platform installed, and since it is the latest one, Unity tries to build with it, but some of the libraries (android.car.jar as an example) was build with Java 11.  This requires a newer JDK and Gradle than Unity uses, which causes the build to fail.  As a workaround, we can uninstall android-33 (the runners have 27 through 33 installed).
***
https://github.com/firebase/firebase-unity-sdk/actions/runs/2792702607
***
***
> Uninstall Android platforms that fail with Unity

- storage/testapp/Assets/Firebase/Sample/Storage/UIHandler.cs
- storage/testapp/Assets/Firebase/Sample/Storage/UIHandlerAutomated.cs
The Storage testapp has been flakey due to a lot of tests assuming downloads will happen faster or slower than they actually do.  Change the tests to use the returned Tasks better, and treat more cases as warnings.
Note there are still some issues in Playmode testing on GHA, and there are still possible other flakes.
***
https://github.com/firebase/firebase-unity-sdk/actions/runs/2885336987
***
***
> Reduce Storage testapp flakiness

- .github/workflows/build_windows.yml
The windows build started failing recently, and the root cause seems to be zlib being installed with mingw. This results in CMake "finding" zlib, and adding it to the include path, which causes issues on the Windows build, as it uses the wrong system headers.  The fix for this is to remove the zlib library prior to the build, since we don't need it anyway.
***
https://github.com/firebase/firebase-unity-sdk/actions/runs/2930380586
***
***
> Remove zlib on Windows build

- cmake/FindUnity.cmake
Currently the build script would automatically find the latest version of Unity unless it is passed with `-unity_root=` parameter.
This change make sure that the build script also check environment variable `UNITY_ROOT_DIR` before searching for the latest version of Unity.
***
Run it locally
***
***
> Check env-var UNITY_ROOT_DIR as well during build

- docs/readme.md
- editor/crashlytics/src/iOSPostBuild.cs
- scripts/gha/integration_testing/XcodeCapabilities.cs
Crashlytics editor tool will not load if the user only adds Android build support to the Unity editor but not iOS build support.  This is because Unity has more restricted validation to function signature when loading dlls.
This fix avoids passing `UnityEditor.iOS.Extensions.Xcode.PBXProject` directly but passing an `object` instead.
Also fixes the integration test script just in case we want to run the test against only one build target.
***
GHA integration test
***
***
> Fix #218 that Firebase editor tool not loading when iOS build support is not installed

- .github/workflows/build_starter.yml
The C++ version input was being ignored and empty string was set instead.
***
Ran this workflow and verified that the Print Outputs step printed outputs.firebase_cpp_sdk_version as a non-empty string
https://github.com/firebase/firebase-unity-sdk/actions/runs/3115233731/jobs/5051915301
***
***
> Update build workflow to use the C++ version input

- app/platform/Unity/PlatformInformation.cs
- app/src/ErrorMessages.cs
- editor/app/src/DocRef.Designer.cs
- editor/app/src/GenerateXmlFromGoogleServicesJson.cs
- editor/app/src/XcodeProjectModifier.cs
- editor/app/src/XcodeProjectPatcher.cs
- editor/crashlytics/src/iOSPostBuild.cs
- firestore/testapp/Assets/Firebase/Editor/Builder.cs
- scripts/gha/integration_testing/AppBuilderHelper.cs
- scripts/gha/integration_testing/XcodeCapabilities.cs
Updates to the Unity build process to handle tvOS pod dependencies and xcode project file configuration.
***
- Local builds on macOS for macOS, iOS and tvOS.
- [Integration Test CI](https://github.com/firebase/firebase-unity-sdk/actions/runs/3183486870)
- [Unity SDK Build CI](https://github.com/firebase/firebase-unity-sdk/actions/runs/3183497310)
***
***
> Unity Editor support for tvOS pods and xcode projects

- .github/workflows/build_tvos.yml
Fixed up workflow to build Unity for tvOS targets.
Workflow is triggered by manual triggers still - and not by the `Firebase Unity SDK build` which kicks-off builds for all of the platforms. This is simply so we don't release the tvOS libraries. Later, when the tvOS release is ready, we'll add this `Build tvOS (SubWorkflow)` to the main build list.
***
- [Build tvOS CI](https://github.com/firebase/firebase-unity-sdk/actions/runs/3234991120)
- Inspected resulting artifact to ensure it contains unity libraries for all of the corresponding products, and that they're in the correct paths.
- Executed `lipo -info` on the resulting static libraries to ensure that they …
> Add workflow that builds tvOS

- scripts/gha/integration_testing/build_testapps.json
- scripts/gha/print_matrix_configuration.py
Updates to `print_matrix_configuration.py` to support tvOS builds in the Integration Test Workflow.  I have not changed the Integration Test workflow to enable tvOS builds by default yet since `build_testapps.py` doesn't yet support tvOs testing (but that's next).
***
Three different methods for testing.
1: [Integration CI run](https://github.com/firebase/firebase-unity-sdk/actions/runs/3292266005) and an [Expanded Matrix Integration Test CI run](https://github.com/firebase/firebase-unity-sdk/actions/runs/3292270698) to ensure I didn't break our current CI flow.
2: Ensured that the existing command line arguments we use to invoke `print_matrix.py` doesn't differ from the main branch. Executed the following …
> Update print_matrix script to support integration test CI

- .github/workflows/integration_tests.yml
XCode 14 gets rid of bitcode support, but some of our dependencies still rely on it, so pin to an older version of xcode until new versions of the dependencies are available.
***
https://github.com/firebase/firebase-unity-sdk/actions/runs/3316431654/jobs/5478220777
***
***
> Fix iOS integration tests failing to build due to bitcode

- .github/workflows/integration_tests.yml
- scripts/gha/build_testapps.py
1. Change the timeout from 50 minutes to 20 (each testapp building process takes less than 12 minutes).
2. Upload build log file artifacts, which are named `testapps-build-logs`.  (log will be print out in the workflow run if there is a failure.)
According to the logs, it seems Crashlytisc missing the following logs and stuck there forever:
```
Generated Firebase Android Resources file Assets\Plugins\Android\FirebaseApp.androidlib\res\values\google-services.xml from D:/a/firebase-unity-sdk/firebase-unity-sdk/testapps2022_11_03-20_12_33/Unity2020.3.34f1-NET4.6/FirebaseAnalytics/testapp/Assets\..\Assets/Firebase/Sample/Analytics/google-services.json
Executed "D:\a\firebase-unity-sdk\firebase-unity-sdk\testapps2022_11_03-20_12_33\Unity2020.3.34f1-NET4.6\FirebaseAnalytics\testapp\Assets\Fireba …
```
> Update build testapp timeout & collect testapp build logs

- .github/workflows/integration_tests.yml
Set output has issues on Windows machine. Fixing it by forcing `shell: bash`.
***
Without forcing bash shell:
https://github.com/firebase/firebase-unity-sdk/actions/runs/3415401417/jobs/5684492872#step:19:3
```
Run actions/upload-artifact@v3
with:
name: testapps-Linux-
path: testapps-/Linux
```
Forcing bash shell:
https://github.com/firebase/firebase-unity-sdk/actions/runs/3415447402/jobs/5684589423#step:19:3
```
Run actions/upload-artifact@v3
with:
name: testapps-Linux-2020-windows-latest-NA
path: testapps-2020-windows-latest-Windows,macOS,Linux-NA/Linux
```
***
***
> Fix set `$GITHUB_OUTPUT` not working on Windows Runners

- .github/workflows/build_android.yml
- .github/workflows/build_ios.yml
- .github/workflows/build_linux.yml
- .github/workflows/build_macos.yml
- .github/workflows/build_tvos.yml
- .github/workflows/build_windows.yml
- .github/workflows/integration_tests.yml
- gha/unity/action.yml
- gha/unity/unity_installer.py
The retry GHA crashes: https://github.com/firebase/firebase-unity-sdk/actions/runs/3403341336/jobs/5659808612
https://github.com/firebase/firebase-unity-sdk/actions/runs/3408235068/jobs/5668638748
Now, retry unity installation process in the Python script.
***
Packaging SDK:
https://github.com/firebase/firebase-unity-sdk/actions/runs/3414744845
https://github.com/firebase/firebase-unity-sdk/actions/runs/3414745614
https://github.com/firebase/firebase-unity-sdk/actions/runs/3414751012
Integration Test:
https://github.com/firebase/firebase-unity-sdk/actions/runs/3414748683
https://github.com/firebase/firebase-unity-sdk/actions/runs/3414747456
In all workflow runs, the unity installation passed with only 1 attempt. (unity been …
> Retry unity installation in Python script instead of using GHA

- .github/workflows/build_android.yml
- .github/workflows/build_ios.yml
- .github/workflows/build_linux.yml
- .github/workflows/build_macos.yml
- .github/workflows/build_tvos.yml
- .github/workflows/build_windows.yml
- .github/workflows/integration_tests.yml
- gha/unity/action.yml
- gha/unity/unity_installer.py
Unity seemingly changed something that has broken u3d, which we were using to install Unity. As a workaround, switch to kuler90/setup-unity, which uses the Unity Hub to install the Unity editor tools instead.
***
SDK build:
https://github.com/firebase/firebase-unity-sdk/actions/runs/3465286169
Integration tests: (Install worked at least)
https://github.com/firebase/firebase-unity-sdk/actions/runs/3464088931
***
***
> Install Unity on GHA with a different tool

- gha/unity/unity_installer.py
The Firestore app fails to build for iOS on CI without the addition of the Unity tvOS build support module. This is true on the `main` branch's [nightly CI run](https://github.com/firebase/firebase-unity-sdk/actions/runs/3512709226/jobs/5884706944).
I could not reproduce this locally. I uninstalled all versions of Unity on my machine to wipe out tvOS support on my host build machine. I then installed Unity and added the modules for macOS, Linux, Android and iOS build support. Building the testapp using command line tools succeeds. I also built the Firebase testapp via the Unit Editor, and that succeeded both the project export and the project compilation for simulators.
Finaly I checked to see if this build …
> Firestore Testapp build fix: add tvos to macOS host unity installations

- .github/workflows/build_windows.yml
The Windows runners recently had Strawberry Perl added, which is causing conflicts when the build searches for zlib. Remove the directory, since we don't depend on it at all.
***
https://github.com/firebase/firebase-unity-sdk/actions/runs/3568935389
***
***
> Remove Strawberry Perl in the Windows build

- .github/workflows/build_linux.yml
- CMakeLists.txt
- cmake/build_aar.cmake
- cmake/firebase_swig.cmake
Use find_program to get the python executable, since it can either by python or python3.
***
https://github.com/firebase/firebase-unity-sdk/actions/runs/3577495692
***
***
> Use find_program to get python in cmake

- docs/readme.md
- remote_config/src/ConfigSettings.cs
Remote Config had a typo in the Config Settings, MinimumFetchInternalInMilliseconds should be Interval (v instead of n).  Add the correct property, and deprecate the old one.
***
Building locally, and https://github.com/firebase/firebase-unity-sdk/actions/runs/3690833620
***
***
> Fix typo in RC Config Settings

- .github/workflows/build_linux.yml
- gha/unity/README.md
- gha/unity/unity_installer.py
Current unity installation process on newer ubuntu runners has an issue: https://github.com/firebase/firebase-unity-sdk/actions/runs/3567833638/jobs/5996016337#step:8:74
Updated Unity Installation process on ubuntu runners based on: https://docs.unity3d.com/hub/manual/InstallHub.html#install-hub-linux
***
https://github.com/firebase/firebase-unity-sdk/actions/runs/3578235575/jobs/6018161702
Also see the comment below
***
***
> Fix Unity installation error on Linux

- crashlytics/src/IOSImpl.cs
- crashlytics/src/cpp/ios/Crashlytics_PrivateHeaders/Crashlytics_Platform.h
- crashlytics/src/cpp/ios/CrashlyticsiOSWrapper.h
- crashlytics/src/cpp/ios/CrashlyticsiOSWrapper.m
Add iOS implementation for Crashlytics on-demand fatals
Note: on main this pr #560 seems block build for iOS https://screenshot.googleplex.com/AuVq3ZxZnpvLDg7, the committed person is OOO now and I'll followup once he comes back from vacation. Any commit before that on main should be able to build the iOS plug-in
> [Crashlytics fatals] Add iOS implementation

- dynamic_links/testapp/Assets/Firebase/Sample/DynamicLinks/UIHandlerAutomated.cs
Two dynamic links tests are constantly failing on mobile platforms:
- TestCreateShortLinkAsync
- TestCreateUnguessableShortLinkAsync
Disable these tests so we can get CI to green.
Track the need to fix these tests in b/264533368
Note: these tests are already disabled on Desktop platforms as they're unsupported in that environment.
***
[Integration Test CI](https://github.com/firebase/firebase-unity-sdk/actions/runs/3844591289)
***
***
> Disable failing Dynamic Links tests on mobile

- crashlytics/src/AndroidImpl.cs
- crashlytics/src/IOSImpl.cs
- crashlytics/src/cpp/ios/Crashlytics_PrivateHeaders/ExceptionModel_Platform.h
- crashlytics/src/cpp/ios/CrashlyticsiOSWrapper.m
Fix iOS fatal for on demand
Add current stack trace if there is empty stack trace in exception
***
Tested exception with stack trace:
https://screenshot.googleplex.com/43Grf4RVMDd5Fzn
Tested exception without stack trace:
https://screenshot.googleplex.com/BNWeCg59nHA46Lt
***
> [crashlytics ondemand fatals]fix the fatal logic

- auth/testapp/Assets/Firebase/Sample/Auth/UIHandler.cs
- crashlytics/testapp/Assets/Firebase/Sample/Crashlytics/UIHandlerAutomated.cs
- database/testapp/Assets/Firebase/Sample/Database/UIHandlerAutomated.cs
- dynamic_links/testapp/Assets/Firebase/Sample/DynamicLinks/UIHandlerAutomated.cs
- messaging/testapp/Assets/Firebase/Sample/Messaging/UIHandlerAutomated.cs
- scripts/gha/integration_testing/XcodeCapabilities.cs
- storage/testapp/Assets/Firebase/Sample/Storage/UIHandlerAutomated.cs
Fixes to the Storage, Database, Crashlytics and Messaging tests. These testapps has variable behavior based on the target device, and use `UNITY_IOS` or `UNITY_ANDROID` preprocessors to toggle off certain tests. These preprocessor definitions are automatically defined for us by Unity when building for the applicable platforms.
This change adds `UNITY_TVOS` where appropriate and makes it use the same tests & code as `UNITY_IOS`.
Additionally the Storage tests that download to disk have been disabled since tvOS does not have a dependable file system to test against.
Flaky tests that failed in CI were Installations, Messaging, and Functions. When verifying these tests locally on tvOS simulators, both …
> Fix tvOS iTests - Use UNITY_TVOS and disable Storage filesystem tests

- crashlytics/src/AndroidImpl.cs
- crashlytics/src/Crashlytics.cs
- crashlytics/src/ExceptionHandler.cs
- crashlytics/src/IOSImpl.cs
- crashlytics/src/Impl.cs
- crashlytics/src/cpp/android/crashlytics_android.cc
- crashlytics/src/cpp/android/crashlytics_android.h
- crashlytics/src/cpp/common/crashlytics.cc
- crashlytics/src/cpp/include/firebase/crashlytics.h
- crashlytics/src/cpp/ios/Crashlytics_PrivateHeaders/Crashlytics_Platform.h
- crashlytics/src/cpp/ios/Crashlytics_PrivateHeaders/ExceptionModel_Platform.h
- crashlytics/src/cpp/ios/CrashlyticsiOSWrapper.h
- crashlytics/src/cpp/ios/CrashlyticsiOSWrapper.m
- crashlytics/src/cpp/stub/crashlytics_stub.cc
- crashlytics/src/cpp/stub/crashlytics_stub.h
Implement Crashlytics Unity ODFs for iOS and Android.
Design doc: [go/crashlytics-unity-fatals](http://go/crashlytics-unity-fatals)
API review: [go/crashlytics-unity-fatals-api](http://go/crashlytics-unity-fatals-api)
> Implement Crashlytics Unity ODFs

- scripts/gha/integration_testing/build_testapps.json
I introduced a bug in our build system with PR #599 where I added an explicit list of build targets for each SDK's testapp. In this change I errantly listed "Desktop" as a possible target, but really desktop is either "Windows, "Linux", or "macOS".
This PR fixes the issue by expanding Desktop entries to those values.
***
[Integration Test CI](https://github.com/firebase/firebase-unity-sdk/actions/runs/3959268929)
***
***
> Fix build_testapp scripts for desktop targets

- scripts/gha/build_testapps.py
Uninstalls both platforms;android-33 and platforms;android-33-ext4 instead of just platforms;android-33
Without this change build_testapps was failing the minify with proguard step for build-2020-windows-latest-Android-NA: [example](https://github.com/firebase/firebase-unity-sdk/actions/runs/3947076744/jobs/6755492933#logs)
***
***
Ran the build_testapps workflow [without](https://github.com/firebase/firebase-unity-sdk/actions/runs/3961567058/jobs/6787161653) and [with](https://github.com/firebase/firebase-unity-sdk/actions/runs/3961935913/jobs/6787979051) this change.
Added list_installed to the script so that the installed platforms is logged and verified that …
> Uninstall platforms;android-33-ext4 when building testapps 

- .github/workflows/build_starter.yml
- .github/workflows/integration_tests.yml
- scripts/gha/print_matrix_configuration.py
Update build system to build tvOS by default.
Change also extends the expanded matrix mode to include tvOS.
***
[Unity Build](https://github.com/firebase/firebase-unity-sdk/actions/runs/3962594440) -> [Integration Test CI](https://github.com/firebase/firebase-unity-sdk/actions/runs/3968213187)
***
***
> Enable tvOS Nightly

- .github/workflows/build_starter.yml
I checked the builds this weekend and notice that the scheduled jobs skipped tvOS. I think I found the reason why.
***
[Ran Unity Build Starter](https://github.com/firebase/firebase-unity-sdk/actions/runs/3986872295) to ensure .yml syntax is correct.
***
***
> Add tvOS to nightly builds

- storage/testapp/Assets/Firebase/Sample/Storage/UIHandlerAutomated.cs
The Storage testapp is a bit flakey due to the amount of uploads and downloads it does. Add the new generic retry logic, so that it will retry tests that fail a few times.
***
https://github.com/firebase/firebase-unity-sdk/actions/runs/4028762567
***
***
> Add retry to the Storage testapp

- app/src/swig/app.i
When Swig generating "%csmethodmodifiers" code block, instead of keeping all preprocesser directives like "#if FIREBASE_PLATFORM_DESKTOP", it seem to preprocess the block directly and remove codes.
In this case, Swig would consider FIREBASE_PLATFORM_DESKTOP never defined and remove the entire block in the generated code, regardless the current build target platform.
The fix is to move the preprocesser directives to a separate C++ function.
***
This can be easily verified with
```
python scripts/build_scripts/build_zips.py --platform=macos --apis=auth
```
***
***
> Fix LogHeartbeatInternal

- crashlytics/src/Crashlytics.cs
Mark LogExceptionAsFatal as internal.
This method is not intended for developers to call directly. https://firebase.google.com/docs/crashlytics/customize-crash-reports?platform=unity#log-excepts
> Mark LogExceptionAsFatal as internal.

- firestore/scripts/cp_unity_dlls.py
Add a new script, `cp_unity_dlls.py`, that makes incremental builds easier to deploy to the testapp. Rather than having to build a unitypackage and import it into the unity project (which takes a loooong time) this script simply copies the dll, so, and bundle files from cmake's "build" directory into the directory of the testapp project, clobbering the files that are already there.
> firestore: add cp_unity_dlls.py script

- analytics/testapp/Assets/Firebase/Sample/Analytics/UIHandlerAutomated.cs
The session id test on Android can randomly fail due to the test infrastructure having potentially old versions of Play Services.  Disable the test on Android, and just rely on the combination of the C++ tests, and the other platforms to guarantee that it is calling into the C++ layer correctly.
***
https://github.com/firebase/firebase-unity-sdk/actions/runs/4379166466
***
***
> Disable Session Id test on Android

- firestore/testapp/Assets/Firebase/Sample/Firestore/UIHandlerAutomated.cs
Add a default retry to the Firestore tests, so that if a test fails, it will retry up to 3 times. Note that the logs will reflect when a test retries, with a warning.
***
https://github.com/firebase/firebase-unity-sdk/actions/runs/4380372493
***
***
> Add automatic retry to the Firestore tests

- cmake/unity_mono.cmake
- scripts/build_scripts/build_zips.py
- Explicitly disable boringssl to use openssl 
- Add netstandard reference to make build success
- Fix the call to `firebase::App::RegisterLibrary` which only have 2 parameter for windows platform
More details in https://github.com/firebase/firebase-unity-sdk/issues/557
***
Run `python ./scripts/build_scripts/build_zips.py --use_boringssl=false --platform=windows` and got zip and dll files result properly without error
***
- [ x ] Bug fix. Add the issue # below if applicable.
- [ x ] Other, such as a build process or documentation change.
***
ps This is cmakesettings.json I need to explicitly configure in my machine
```json
{ …
```
> fix for build windows

- scripts/gha/build_testapps.py
This is effectively the same as #604, but for another extension of android 33.
Without this change build_testapps fails the minify with proguard step for build-2020-windows-latest-Android-NA: example: https://github.com/firebase/firebase-unity-sdk/actions/runs/4559389559/jobs/8043295718
This is the same fix as for a previous version of the same issue.
***
***
> Uninstall platforms;android-33-ext5 when building testapps

- app_check/CMakeLists.txt
- app_check/src/AppCheckError.cs
- app_check/src/AppCheckToken.cs
- app_check/src/FirebaseAppCheck.cs
- app_check/src/IAppCheckProvider.cs
- app_check/src/IAppCheckProviderFactory.cs
- app_check/src/TokenChangedEventArgs.cs
Adds the files that make up most of the public App Check API (minus the built-in providers).  Most of the functionality is not implemented, that will be in follow up PRs.
***
It builds locally.
***
***
> Add the public App Check API files

- auth/src/PhoneAuthProvider.cs
- auth/src/swig/auth.i
- swig_post_process.py
Initial change to make sure Unity SDK can compile against C++ Auth feature branch.
Integration test is expected to be broken since it is pointing to C++ main and Unity integration test is not update.
This change includes:
- Update SWIG postprocess to rename deprecated functions which returns a `Task`
- Remove `PhoneAuthProvider.MaxTimeoutMs`
- Wire the following function to new C++ impl
- `Firebase.Auth.FirebaseAuth.CurrentUser`
- `Firebase.Auth.FirebaseUser.ProviderData`
- Deprecated the following function
- Firebase.Auth.FirebaseAuth.SignInWithCustomTokenAsync_DEPRECATED
- Firebase.Auth.FirebaseAuth.SignInWithCredentialAsync_DEPRECATED
- Firebase.Auth.FirebaseAuth.SignInAndRetrieveDataWithCredentialAsync_DE …
> Initial change for Auth Google/IO changes to just fix the compiler error

- CMakeLists.txt
- scripts/build_scripts/build_zips.py
Update the C++ version to 14, and when doing a GHA windows build, use a newer version of the Windows SDK (the same used by the C++ repo).  This is to fix the issues with building grpc.
***
https://github.com/firebase/firebase-unity-sdk/actions/runs/4801338273
***
***
> Update C++ version and use newer Windows SDK

- cmake/firebase_unity_version.cmake
- unity_packer/exports.json
Rollup EDM4U version to 1.2.176 which includes the many fixes in Android resolver. More detail [here](https://github.com/googlesamples/unity-jar-resolver/releases/tag/v1.2.176)
***
N/A
***
***
> Rollup EDM4U version to 1.2.176

- scripts/gha/requirements.txt
EDM4U removed the deprecated use of `distutil` and migrated to `packaging`. Add this as a required Python package.
***
Local test
***
***
> Add new required Python package for EDM4U

- CMakeLists.txt
- auth/src/PhoneAuthProvider.cs
- auth/src/swig/auth.i
- auth/testapp/Assets/Firebase/Sample/Auth/UIHandler.cs
- auth/testapp/Assets/Firebase/Sample/Auth/UIHandlerAutomated.cs
- firestore/testapp/Assets/Firebase/Sample/Firestore/UIHandlerAutomated.cs
- firestore/testapp/Assets/Tests/FirestoreInstanceTests.cs
- functions/testapp/Assets/Firebase/Sample/Functions/UIHandlerAutomated.cs
Rename and deprecated the following methods
- `FirebaseUser.LinkAndRetrieveDataWithCredentialAsync_DEPRECATED()`
- `FirebaseUser.LinkWithCredentialAsync_DEPRECATED()`
- `FirebaseUser.ReauthenticateAndRetrieveDataAsync_DEPRECATED()`
- `FirebaseUser.UnlinkAsync_DEPRECATED()`
- `FirebaseUser.UpdatePhoneNumberCredentialAsync_DEPRECATED()`
- `PhoneAuthProvider.VerificationCompleted_DEPRECATED`
- `PhoneAuthProvider.VerifyPhoneNumber()`
- `PhoneAuthProvider.GetCredential_DEPRECATED()`
Update existing tests to use deprecated APIs. Some will be changed to use the new API once available.
***
GA
Build: https://github.com/firebase/firebase-unity-sdk/actions/runs/4814057808
*** …
> Remaining Auth deprecated APIs for Google I/O

- docs/readme.md
- messaging/src/swig/messaging.i
Remove calls from messaging that have been deprecated for several years now.
***
Builds locally.
***
***
> Remove deprecated Messaging calls

- auth/src/PhoneAuthProvider.cs
- auth/src/swig/auth.i
- `PhoneAuthCredential.SmsCode`
- `PhoneAuthProvider.VerificationCompleted(PhoneAuthCredential)`
- `PhoneAuthProvider.GetCredential()`
- `PhoneAuthProvider.VerifyPhoneNumber(PhoneAuthOptions, VerificationCompleted, VerificationFailed, CodeSent, CodeAutoRetrievalTimeOut)`
Quite a bit work for `PhoneAuthProvider.VerificationCompleted()` so made a separate PR dedicated for this.
***
GHA
https://github.com/firebase/firebase-unity-sdk/actions/runs/4888753520
***
***
> New APIs for PhoneAuthCredential and PhoneAuthProvider

- auth/src/FirebaseAccountLinkException.cs
- auth/src/PhoneAuthProvider.cs
- auth/src/swig/auth.i
Properly implement `AuthResult` and add the following methods which returns `Task<AuthResult>`
- `FirebaseAuth.SignInWithCustomTokenAsync()`
- `FirebaseAuth.SignInWithCredentialAsync()`
- `FirebaseAuth.SignInWithProviderAsync()`
- `FirebaseAuth.SignInAndRetrieveDataWithCredentialAsync()`
- `FirebaseAuth.SignInAnonymouslyAsync()`
- `FirebaseAuth.SignInWithEmailAndPasswordAsync()`
- `FirebaseAuth.CreateUserWithEmailAndPasswordAsync()`
- `FirebaseUser.ReauthenticateAndRetrieveDataAsync()`
- `FirebaseUser.ReauthenticateWithProviderAsync()`
- `FirebaseUser.LinkWithCredentialAsync()`
- `FirebaseUser.LinkWithProviderAsync()`
- `FirebaseUser.UnlinkAsync()`
- `FirebaseUser.UpdatePhoneNumberCredentialAsync()`
- Remove …
> Add new Auth APIs using `AuthResult`

- auth/src/swig/auth.i
Deprecate `UserInfoInterface.phone_number` and introduce `UserInfoInterface.PhoneNumber` instead.
***
GHA
https://github.com/firebase/firebase-unity-sdk/actions/runs/4890907944
***
***
> Deprecate `UserInfoInterface.phone_number` and introduce `UserInfoInterface.PhoneNumber` instead.

- remote_config/testapp/Assets/Firebase/Sample/RemoteConfig/UIHandler.cs
- remote_config/testapp/Assets/Firebase/Sample/RemoteConfig/UIHandlerAutomated.cs
Add GUI buttons to enable and disable auto-fetch by adding and removing config a update listener.
Add an automated test to verify that the config update listener is called with the correct keys.
Update an existing test to assert the fetched values.
***
Ran testapp on a local android device and local ios simulator.
***
***
> Update RemoteConfig testapp to use the new Realtime methods

- auth/src/swig/auth.i
Currently
C++ Auth User has
provider_data()     std::vector< UserInfoInterface >
[provider_data_DEPRECATED](https://firebase.google.com/docs/reference/cpp/class/firebase/auth/user#provider_data_deprecated)()      std::vector< UserInfoInterface * > &
Unity Auth FirebaseUser has
ProviderData    IEnumerable< IUserInfo >
[provider_data_DEPRECATED](https://firebase.google.com/docs/reference/unity/class/firebase/auth/firebase-user#provider_data_deprecated)()     SWIGTYPE_p_std__vectorT_firebase__auth__UserInfoInterface_p_t
Since the type for Unity ProviderData has not changed as part of the 11.0.0 release, the Unity provider_data_DEPRECATED field can just be deleted.
***
Built Auth locally and inspected the generated C# code. Verified that the provider_data_DEPRECATED method is no longer …
> Remove accidentally swig generated field FirebaseUser.provider_data_DEPRECATED

- auth/src/swig/auth.i
- docs/readme.md
- swig_post_process.py
Hide accidentally exposed methods by making both methods ended with `InternalAsync` and `InternalAsync_DEPRECATED` internal automatically through SWIG post process.
Also, duplicated SWIG code for `PhoneAuthCredential.SmsCode`
***
GHA
Build: https://github.com/firebase/firebase-unity-sdk/actions/runs/4955353780
Test: TBD
***
***
> Make methods end with `InternalAsync` internal

- docs/readme.md
- scripts/create_debug_export.py
- unity_packer/debug_single_export_json/analytics.json
- unity_packer/debug_single_export_json/app_check.json
- unity_packer/debug_single_export_json/auth.json
- unity_packer/debug_single_export_json/crashlytics.json
- unity_packer/debug_single_export_json/database.json
- unity_packer/debug_single_export_json/dynamic_links.json
- unity_packer/debug_single_export_json/firestore.json
- unity_packer/debug_single_export_json/functions.json
- unity_packer/debug_single_export_json/installations.json
- unity_packer/debug_single_export_json/messaging.json
- unity_packer/debug_single_export_json/remote_config.json
- unity_packer/debug_single_export_json/storage.json
- unity_packer/exports.json
Update exports.json to match App-* and App.* instead of App*
Fix create_debug_export.py and run it.
This is relevant because previously App* was matching FirebaseCppAppCheck.bundle, when the pattern was meant to match files like FirebaseCppApp-11_0_0.bundle. As a result the App tgz was unintentionally including AppCheck files.
***
Build workflow based on this PR
https://github.com/firebase/firebase-unity-sdk/actions/runs/4996447348
Verified that the app.tgz produced by that build does not have redundant appcheck bundles.
***
***
> Update Unity export so that App does not include AppCheck files

- auth/src/swig/auth.i
- docs/readme.md
Caching the currentUser seems to be causing problems when checking the cached version's validity.  Removing the cache, since it isn't being used for anything beyond Disposing, which the garbage collection should handle.
Should address: https://github.com/firebase/firebase-unity-sdk/issues/733
***
https://github.com/firebase/firebase-unity-sdk/actions/runs/5094756381
***
***
> Remove the Auth currentUser cache

- app/src/swig/app.i
GetApps was recently added to C++, but isn't intended to be part of the Unity API for now, so ignore it.
***
Building locally.
***
***
> Ignore GetApps since it is meant to be internal

- scripts/gha/build_testapps.py
Increase the timeout to 30 minutes when building the iOS and tvOS Firestore testapp, since it has routinely been hitting that.
***
https://github.com/firebase/firebase-unity-sdk/actions/runs/5216934710
***
***
> Increase timeout for building Firestore testapp

- messaging/activity/FirebaseMessagingActivityGenerator.cs
Currently, the class fails to compile in versions of Unity below 2023. Wrapping the `UNITY_2023_1_OR_NEWER` directive around BaseGameActivityClass solves the problem.
It compiles.
- [ x] Bug fix. Add the issue # below if applicable.
***
> Wraps UNITY_2023_1_OR_NEWER directive around BaseGameActivityClass

- docs/readme.md
Update readme.md for 11.2.0
***
N/A
***
***
> Update readme.md for 11.2.0

- scripts/gha/build_testapps.py
The GHA machines added android-34, which has problems with the Unity Android build when using proguard.
***
***
***
> Uninstall android-34 on the GHA machines

- scripts/gha/build_testapps.py
This generalizes some previous changes (#604) that uninstalled android platform 33 to also uninstall newer versions.
Recent GitHub runners have had android platform 34 installed.
This also changes from list_installed to list as when I tested locally, list_installed was not a recognized command. List outputs installed and available.
***
Build with this change
https://github.com/firebase/firebase-unity-sdk/actions/runs/5360532633
***
***
> Uninstall all versions of android platform 33 or newer

- scripts/gha/test_simulator.py
Add logic to check which versions of iOS/tvOS are available, and fallback to the latest if the requested one isn't available. Also change to using xcodes to install iOS simulators, since xcode-install has been deprecated in favor of it.
***
Running locally, and https://github.com/firebase/firebase-unity-sdk/actions/runs/5395850671
***
***
> Improve the iOS simulator install logic

- docs/readme.md
- firestore/testapp/Assets/Firebase/Sample/Firestore/UIHandlerAutomated.cs
Add a test and release notes entry for a fix to an intermittent crash in Firestore on Android when large documents and/or a large number of documents with large arrays or maps were used. See https://github.com/firebase/firebase-unity-sdk/issues/569 and https://github.com/firebase/firebase-cpp-sdk/pull/1364 for details.
> Firestore: Add a test and readme about the android global refs crash

- .github/workflows/integration_tests.yml
When using a previously packaged SDK, the integration test should log what GitHub run_id it was created with.
This will be used by the build report script to match integration test runs with scheduled package builds, as we do in C++.
***
[Manually run workflow](https://github.com/firebase/firebase-unity-sdk/actions/runs/5480308755)
***
***
> Log previous run ID in workflow.

- scripts/gha/integration_testing/test_validation.py
Test logs were not correctly parsing testapp paths like "/home/runner/work/firebase-unity-sdk/firebase-unity-sdk/testapps/iOS/app_check/FirebaseAppCheckUnityTestapp.ipa" into "app_check" because it was assuming that testapp paths would remove the underscore, like remoteconfig. But app_check does not do this, so add an additional check including the underscore.
***
When app_check iOS has a failure, we'll confirm that this worked.
***
***
> Fix app_check testapp name.

- .github/workflows/build_tvos.yml
- scripts/build_scripts/build_zips.py
The tvOS configuration updates the Cocoapods, which writes to a shared cache location. Run the configuration in sequence, so that the device and simulator builds don't accidentally clobber each other while doing this, but the build and package step can still be done in parallel.
***
Just tvOS: https://github.com/firebase/firebase-unity-sdk/actions/runs/5534351005
Full package: https://github.com/firebase/firebase-unity-sdk/actions/runs/5526425595
***
***
> Run tvOS configuration in sequence

- dynamic_links/testapp/Assets/Firebase/Sample/DynamicLinks/UIHandler.cs
- dynamic_links/testapp/Assets/Firebase/Sample/DynamicLinks/UIHandlerAutomated.cs
Dynamic Links set up requires the URLs being used to be part of the allowlist for the project, as set in the Firebase Console. 
Change the urls in the dynamic links testapp to use links that are in the allowlist for the project, and re-enable the disabled tests on mobile, since that was causing the problem.
***
https://github.com/firebase/firebase-unity-sdk/actions/runs/5536178528
***
***
> Fix dynamic link tests on mobile

- analytics/testapp/Assets/Firebase/Sample/Analytics/UIHandlerAutomated.cs
- scripts/gha/integration_testing/build_testapps.json
Installations was failing on simulators because of confusion around fis and installations.  Analytics was failing to get the session id on simulators, which is a known problem, and the test is disabled on the C++ side, so do the same here.
***
https://github.com/firebase/firebase-unity-sdk/actions/runs/5581346312
***
***
> Fix Installations and Analytics testapp problems

- scripts/gha/build_testapps.py
- scripts/gha/integration_testing/AppBuilderHelper.cs
Occasionally the iOS testapps fail on device because they are asking for local network permissions. This seems to be triggered by Unity development mode, which would allow machine access to the device, for debugging purposes.  Disable that setting when building iOS device tests for CI, to see if that improves things.
***
https://github.com/firebase/firebase-unity-sdk/actions/runs/5591444715
***
***
> Don't enable development on iOS device CI builds

- scripts/gha/desktop_tester.py
The linux logs seem to fail when printing out too much information, so limit the size of the logs.
***
https://github.com/firebase/firebase-unity-sdk/actions/runs/5593161169
***
***
> Truncate the logs on Linux tests

- messaging/testapp/Assets/Firebase/Sample/Messaging/UIHandler.cs
- messaging/testapp/Assets/Firebase/Sample/Messaging/UIHandlerAutomated.cs
Change the Messaging topic test to subscribe, send, and unsubscribe in the same test.  This is to prevent accidentally receiving a topic test while running a different test.  Ideally it would use a more unique test topic, but creating a test topic takes some time after creation before it can be used to send messages.
***
https://github.com/firebase/firebase-unity-sdk/actions/runs/5604605972
***
***
> Change the Messaging topic test to avoid accidental messages

- scripts/gha/integration_testing/automated_testapp/AutomatedTestRunner.cs
A test should only print a warning log about how a test took multiple attempts to pass if it actually passed in the end.
***
***
***
> Only print passing warning log if test passes

- cmake/firebase_unity_version.cmake
- unity_packer/debug_single_export_json/analytics.json
- unity_packer/debug_single_export_json/app_check.json
- unity_packer/debug_single_export_json/auth.json
- unity_packer/debug_single_export_json/crashlytics.json
- unity_packer/debug_single_export_json/database.json
- unity_packer/debug_single_export_json/dynamic_links.json
- unity_packer/debug_single_export_json/firestore.json
- unity_packer/debug_single_export_json/functions.json
- unity_packer/debug_single_export_json/installations.json
- unity_packer/debug_single_export_json/messaging.json
- unity_packer/debug_single_export_json/remote_config.json
- unity_packer/debug_single_export_json/storage.json
- unity_packer/exports.json
Update EDM4U dependency to 1.2.177, which fix iOS resolver issue on M1 mac.
See https://github.com/googlesamples/unity-jar-resolver/releases/tag/v1.2.177
***
GHA
***
***
> Update EDM4U deps to 1.2.177

- auth/CMakeLists.txt
- auth/src/FirebaseUser.cs
- auth/src/swig/auth.i
- auth/testapp/Assets/Firebase/Sample/Auth/UIHandlerAutomated.cs
- docs/readme.md
The C++ object for FirebaseUser isn't reliable enough in memory for the C# object to hold onto a reference to it (for example, if the AuthResult is deleted, the User will be as well).  Some users were seeing crashes being caused by this.
Fix it by fetching the C++ object when needed, which guarantees that it will be a valid C++ object.
***
https://github.com/firebase/firebase-unity-sdk/actions/runs/5863182504
***
***
> Refactor FirebaseUser to handle C++ objects better

- app/src/swig/future.i
About once a week Installations tests seem to fail because of a race condition around completing Tasks that the underlying Future is already completed.  The problem seems to be that when registering the C++ callback, it completes immediately, thus deleting the Future object while C# is still working with it.  Fix this by checking if the object has been Disposed, and handling it, instead of throwing an exception.
***
https://github.com/firebase/firebase-unity-sdk/actions/runs/5968360487
***
***
> Handle Future completion race condition

- messaging/testapp/Assets/Firebase/Sample/Messaging/UIHandler.cs
- messaging/testapp/Assets/Firebase/Sample/Messaging/UIHandlerAutomated.cs
The OnTokenReceived callback is only called for new Messaging Tokens, so if the App has a cached token, it would not receive a new token, and thus the tests would timeout while waiting for it.  Change the tests to use GetTokenAsync if necessary to get a token, and throw exceptions if the token is still missing.
***
https://github.com/firebase/firebase-unity-sdk/actions/runs/6028673810
***
***
> Change how Messaging testapp gets registration token

- messaging/activity/FirebaseMessagingActivityGenerator.cs
The Unity 2023.2 beta is seemingly removing mUnityActivity's quit().  Change it to use destroy(), which should have the same overall effect.
***
https://github.com/firebase/firebase-unity-sdk/actions/runs/6043471004
***
***
https://github.com/firebase/firebase-unity-sdk/issues/842
> Change how Messaging Activity cleans up in 2023

- scripts/gha/build_testapps.py
Add logic to retry playmode tests.  These tests are generally a bit flakey, so add logic to retry the tests a couple of times, to account for this flakiness. Note that we do something similar in the C++ repo already.
***
https://github.com/firebase/firebase-unity-sdk/actions/runs/6031700442
***
***
> Add logic to retry playmode tests

- scripts/gha/report_build_status.py
The regex check to split firestore and not depended on the lines ending with a newline, so add an extra newline to the text to parse beforehand.
***
***
***
> Fix build report not parsing the last line

- .github/workflows/integration_tests.yml
- analytics/testapp/Assets/Firebase/Sample/Analytics/UIHandlerAutomated.cs
- scripts/gha/__init__.py
- scripts/gha/integration_testing/__init__.py
- scripts/gha/read_ftl_test_result.py
Add retry attempts to the FTL integration tests running on GHA, to work around device flakiness.  Adds a custom validator, since the FTL run reports success regardless of if the tests contained succeeded or failed.
***
Run with intentional failure to see the retries: https://github.com/firebase/firebase-unity-sdk/actions/runs/6475956332
Normal run: https://github.com/firebase/firebase-unity-sdk/actions/runs/6476383922
***
***
> Add retries to the FTL integration test runs

- app_check/src/FirebaseAppCheck.cs
- docs/readme.md
The Unity class was not returning after calling into C++ when dealing with an error, which could accidentally result in multiple callbacks, which would raise an error.
***
https://github.com/firebase/firebase-unity-sdk/actions/runs/6473902284
***
***
https://github.com/firebase/firebase-unity-sdk/issues/877
> Fix App Check crash if there is a config problem

- cmake/firebase_unity_version.cmake
Fix for #886.
Based on the [release notes](https://firebase.google.com/support/release-notes/unity#version_1160_-_october_19_2023), it seems that the CocoaPods version was updated to 10.6.0 but it didn't reflect to the latest SDK version.
> Update Cocoapods version to 10.6.0

- firestore/src/AggregateSource.cs
- firestore/src/Query.cs
Apply the feedback to the count API documentation as suggested in https://github.com/firebase/firebase-js-sdk/pull/6608. This is a port of https://github.com/firebase/firebase-js-sdk/pull/7933.
> Firestore: Small Count API documentation improvements

- .github/workflows/integration_tests.yml
- scripts/gha/print_matrix_configuration.py
Update matrix script to allow multiple FTL devices of each type, and update to a newer firebase-test-lab action that allows randomizing devices.
***
https://github.com/firebase/firebase-unity-sdk/actions/runs/7494588317/job/20405319450#step:11:120
***
***
> Enable FTL device randomization for Android and iOS.

- .github/workflows/build_android.yml
- app/src/swig/app.i
- app/src/swig/future.i
- firestore/src/swig/firestore.i
Newer versions of swig changed some logic around preprocessors that causes future to fail how it was handling void types.
***
https://github.com/firebase/firebase-unity-sdk/actions/runs/7730685234
***
***
> Update future swig file preprocessor logic

- .github/workflows/integration_tests.yml
- editor/app/CMakeLists.txt
- editor/app/src/AnalyticsFixPropertyRemover.cs
Android Analytics has added a special <property> tag to its AndroidManifest file, which requires a newer version of Gradle than most Unity versions ship with.  Add logic to remove the tag by default, and if users want to maintain the tag they can by following the instructions in the modified AndroidManifest file that this logic creates.
***
Testing in other branches, since this also requires changes to EDM4U that aren't in yet for Android to fully work.
This branch:
https://github.com/firebase/firebase-unity-sdk/actions/runs/7850328827
***
***
> Remove property tags from Android builds

- docs/readme.md
- editor/app/src/AnalyticsFixPropertyRemover.cs
Improve the logic to only add the property removeAll tag if the gradle version being used is old enough that it doesn't support the property tag in the manifest merger.  By default this should apply to Unity 2022+.
***
Testing this locally across both older and newer Unity versions.
***
***
https://github.com/firebase/firebase-unity-sdk/issues/945
> Improve logic around removeAll tag and newer gradle versions

- auth/src/FirebaseUser.cs
- docs/readme.md
Add FirebaseUser.SendEmailVerificationBeforeUpdatingEmailAsync, which is the new method to update user emails,
and deprecate UpdateEmailAsync, which no longer works when Email Enumeration Protection is turned on.
***
Building and testing locally, plus
https://github.com/firebase/firebase-unity-sdk/actions/runs/8103734621
***
***
> Add new method to update Auth User's email

- scripts/gha/print_matrix_configuration.py
The GHA machines have been giving errors on Mac when trying to build the Android testapps, primarily around NDK and JDK issues.  Disable these tests for now, until we can track down the root cause of the issue.
***
https://github.com/firebase/firebase-unity-sdk/actions/runs/8760959333
***
***
> Temporarily remove the Android on Mac test runs

- scripts/gha/build_testapps.py
The testapp builder has occasionally been having issues where after one Unity call (with -quit), when it gets to the next call Unity still seems to be running, causing an error.  Adding a small sleep, to give the previous call a chance to close properly.
***
***
***
> Add sleeps after Unity calls in testapp builder

- docs/readme.md
- remote_config/src/ConfigSettings.cs
Remove the deprecated ConfigSettings.MinimumFetchInternalInMilliseconds in prep for the next major release, as it has been deprecated for more than a year now.  Use ConfigSettings.MinimumFetchIntervalInMilliseconds instead (the difference is Internal vs Interval).
***
***
***
> Remove deprecated RC ConfigSettings field

- .github/workflows/build_android.yml
- .github/workflows/build_macos.yml
- scripts/gha/print_matrix_configuration.py
macos-latest used to refer to macos-12, but has since changed to macos-14-arm64.  It'll take some effort to upgrade the logic for that jump, so for now pin back to 12.
***
https://github.com/firebase/firebase-unity-sdk/actions/runs/8824930809
***
***
> Pin the mac runners to 12

- firestore/src/Converters/AttributedTypeConverter.cs
When an annotated class is set to `UnknownPropertyHandling.Throw`, an unexpected exception is thrown rather than the intended readable one. `string.Format()` has an invalid format string, as it expects exclusively argument indexes.
***
Tested by running the same scenario with the patch, and the expected exception is thrown to the calling code.
***
***
> Fix formatting exception for unknown property

- .github/workflows/integration_tests.yml
There was an issue with tvOS builds and XCode 15, here:
https://issuetracker.unity3d.com/issues/tvos-unable-to-build-any-tvos-project-using-xcode-15-beta
We still run tests on a 2020 version, so we can duplicate the fix in the workflow as a workaround.
***
https://github.com/firebase/firebase-unity-sdk/actions/runs/8993239723
***
***
> Add a workaround to tvOS testapp build

- .github/workflows/integration_tests.yml
- .github/workflows/retry-test-failures.yml
- scripts/gha/firebase_github.py
- scripts/gha/retry_test_failures.py
- scripts/gha/trigger_workflow.py
It will retry all **build** errors that match timeout/network error regexes, but not any compiler errors or other issues. (If there are other instances in which the builds sometimes fail transiently, we can add that.)
Not sure under what conditions to actually trigger the **test** retry, so it does it unconditionally.
***
Tested manually with the "scheduled_trigger" check in integration_tests.yaml commented out, and failure forced.
This run: https://github.com/firebase/firebase-unity-sdk/actions/runs/9087398748
***
***
> Retry test failures on Unity

- scripts/gha/build_testapps.py
Sometimes the Unity editor test logs have an invalid character for utf-8, which causes errors.  Add some error handling, replacing any bad characters discovered.
***
https://github.com/firebase/firebase-unity-sdk/actions/runs/9182014476
***
***
> Add a workaround for invalid test logs

- analytics/src/swig/analytics.i
- docs/readme.md
Add the logic for the new Analytics On-Device Conversion Measurement methods that take in hashed byte arrays.
***
https://github.com/firebase/firebase-unity-sdk/actions/runs/9523633148
***
***
> Add new Analytics OnDevice Conversion methods

- .github/workflows/integration_tests.yml
- remote_config/testapp/Assets/Firebase/Sample/RemoteConfig/UIHandlerAutomated.cs
- scripts/gha/print_matrix_configuration.py
Disable tests that require Remote Config fetching on iOS simulator devices.  This keeps timing out on the GHA runners for some reason, but not locally, and not on the C++ tests, so it is likely some configuration issue that will need more time to track down.
***
https://github.com/firebase/firebase-unity-sdk/actions/runs/9557339261
***
***
> Modify RC tests for iOS simulators

- app_check/src/FirebaseAppCheck.cs
The reference documentation was failing to parse the special tags in FirebaseAppCheck, so remove them.
***
***
***
> Fix App Check documentation

- docs/readme.md
- messaging/CMakeLists.txt
- messaging/src/FirebaseMessage.cs
- messaging/src/FirebaseMessaging.cs
- messaging/src/FirebaseNotification.cs
- messaging/src/MessagingEventArgs.cs
- messaging/src/MessagingOptions.cs
- messaging/src/swig/messaging.i
Rewrite the Messaging Swig logic, so that the public API is in handwritten C# files, and the generated code is instead internal logic to be called.  This fixes a handful of missing docs generation issues, and deprecates the Dispose/Disposing calls, since those are no longer necessary to expose at all.
***
Confirmed the docs generation looks correct by hand
https://github.com/firebase/firebase-unity-sdk/actions/runs/9964644977
***
***
> Rewrite Messaging Swig logic to prefer handwritten public files

- firestore/testapp/Assets/Firebase/Sample/Firestore/UIHandlerAutomated.cs
One of the Firestore tests is failing to respect the cache settings.  Disable until a proper fix can be found.
***
***
***
> Disable Firestore cache test for now

- docs/readme.md
- messaging/src/FirebaseNotification.cs
- messaging/src/swig/messaging.i
Add missing null checks to new Messaging conversion logic, and improve the swig conversion logic to better handle if an exception is thrown, to prevent a double free.  This was causing a crash when opening a notification.
***
Running locally.
GHA: https://github.com/firebase/firebase-unity-sdk/actions/runs/10691311630
***
***
https://github.com/firebase/firebase-unity-sdk/issues/1091
> Add null checks, and improve swig error handling

- .github/workflows/build_android.yml
- .github/workflows/build_ios.yml
- .github/workflows/build_macos.yml
- .github/workflows/build_tvos.yml
The brew install logic is failing to find the specified swig version. Use the latest stable instead.
***
***
***
> Remove version specifier from brew swig logic

- analytics/src/Parameter.cs
- analytics/testapp/Assets/Firebase/Sample/Analytics/UIHandler.cs
- analytics/testapp/Assets/Firebase/Sample/Analytics/UIHandlerAutomated.cs
- docs/readme.md
Adds support for Analytics Parameters to take in Dictionaries and Lists of Dictionaries, which is needed for some Analytics events like ViewCart.
Most of the logic is in C++ here:
https://github.com/firebase/firebase-cpp-sdk/pull/1660
This has been a long missing feature, recently tracked via:
https://github.com/firebase/firebase-unity-sdk/issues/1056
***
***
***
> Add support for Analytics Parameters of Lists

- cmake/firebase_swig.cmake
- docs/readme.md
SWIG 4.3 added a class SWIGStringWithLengthHelper, https://github.com/swig/swig/blob/d9edb22d1c896186b41505376c77a2d296447396/Lib/csharp/csharphead.swg#L329, which is causing some users to have build errors, because it isn't defining the native symbols correctly. Disable it via the provided compile flag, which should prevent it from adding the C# symbols, and the dependency on the missing C++ symbols.
Bug: https://github.com/firebase/firebase-unity-sdk/issues/1139
***
Verifying that the generated output is missing the C# symbols
https://github.com/firebase/firebase-unity-sdk/actions/runs/11826822953
***
***
> Disable new SWIG string helper functions

- .github/workflows/integration_tests.yml
The nightlies run additional workflows, which were conflicting, so make the log names more unique.
***
***
***
> Make workflow uploads more unique

- firestore/CMakeLists.txt
- firestore/src/swig/CMakeLists.txt
Windows defines min/max macros which can cause build issues, which are normally disabled by setting NOMINMAX. We do this a lot in C++, but a recent change in the iOS repo exposes the problem at the Unity level, so add it here as well.
***
https://github.com/firebase/firebase-unity-sdk/actions/runs/13294040512
***
***
> Set NOMINMAX for Firestore Windows builds

- cmake/build_shared.cmake
- cmake/build_universal.cmake
- docs/readme.md
Android 15 is starting to support 16 KB page sizes, which in turn requires shared libraries to be built to support them. Update the shared libraries to it, based on instructions from https://developer.android.com/guide/practices/page-sizes
Might fix https://github.com/firebase/firebase-unity-sdk/issues/1180, but haven't been able to reproduce the initial problem reliably to test.
***
Checking the shared libraries after building via llvm-objdump, again as instructed on that page.
***
***
> Support 16 KB page sizes on Android

- vertexai/testapp/Assets/Firebase/Sample/VertexAI/UIHandlerAutomated.cs
Adds tests for sending and receiving simple text to the model. Adds internal tests to verify parsing the response json.
Note: The internal tests require using the code as a source library, which won't work on GHA yet.
***
***
***
> VertexAI - Add tests about Text, and Json parsing

- scripts/gha/integration_testing/build_testapps.json
- unity_packer/debug_single_export_json/vertexai.json
- vertexai/CMakeLists.txt
- vertexai/src/Candidate.cs
- vertexai/src/Candidate.cs.meta
- vertexai/src/Chat.cs.meta
- vertexai/src/Citation.cs
- vertexai/src/Citation.cs.meta
- vertexai/src/CountTokensResponse.cs.meta
- vertexai/src/FunctionCalling.cs.meta
- vertexai/src/GenerateContentResponse.cs
- vertexai/src/GenerateContentResponse.cs.meta
- vertexai/src/GenerationConfig.cs
- vertexai/src/GenerationConfig.cs.meta
- vertexai/src/GenerativeModel.cs
- vertexai/src/GenerativeModel.cs.meta
- vertexai/src/Internal.meta
- vertexai/src/Internal/InternalHelpers.cs.meta
- vertexai/src/ModelContent.cs
- vertexai/src/ModelContent.cs.meta
- vertexai/src/RequestOptions.cs
- vertexai/src/RequestOptions.cs.meta
- vertexai/src/Safety.cs
- vertexai/src/Safety.cs.meta
- vertexai/src/Schema.cs.meta
- vertexai/src/VertexAI.cs.meta
- vertexai/src/VertexAIException.cs.meta
Since the VertexAI library will be a pure C# library, package the source code directly, instead of prebuilding it to a DLL. This will also users to have an easier time debugging, and allow the integration tests to test some of the internal logic.
The caveat here is that the "internal" keyword no longer does anything, and technically those are visible to users. Thus, we will add comments that they are meant for internal use, and they will still be excluded from reference docs.
Also, add VertexAI to the automated test logic, and fill out more of ModelContent parts
***
GHA build: https://github.com/firebase/firebase-unity-sdk/actions/runs/13533744685
GHA tests: …
> VertexAI - Change packaging logic to use a source library

- .github/workflows/build-report.yml
- .github/workflows/build_android.yml
- .github/workflows/build_ios.yml
- .github/workflows/build_linux.yml
- .github/workflows/build_macos.yml
- .github/workflows/build_starter.yml
- .github/workflows/build_tvos.yml
- .github/workflows/build_windows.yml
- .github/workflows/generate_swig.yml
- .github/workflows/integration_tests.yml
- .github/workflows/retry-test-failures.yml
Workflows call each other, so give them all write permissions.
***
***
***
> Give all workflows write permissions

- .github/workflows/build_android.yml
- .github/workflows/build_ios.yml
- .github/workflows/build_linux.yml
- .github/workflows/build_macos.yml
- .github/workflows/build_tvos.yml
- .github/workflows/build_windows.yml
- .github/workflows/generate_swig.yml
- .github/workflows/integration_tests.yml
Change CMake to an explicit version to avoid incompatibility with new GitHub default version CMake 4.
***
***
***
> Install CMake 3.31.x on runners to override new GitHub default of CMake 4.

- vertexai/src/GenerativeModel.cs
- vertexai/src/Internal/FirebaseInterops.cs
- vertexai/src/Internal/FirebaseInterops.cs.meta
- vertexai/src/LiveGenerativeModel.cs
Add support for including the AppCheck token to the VertexAI calls. Uses reflection to get the token, since it isn't guaranteed that the user will include AppCheck.
***
Running locally both with and without AppCheck in the project.
***
***
> [VertexAI] Add AppCheck token support

- vertexai/src/GenerationConfig.cs
- vertexai/testapp/Assets/Firebase/Sample/VertexAI/UIHandlerAutomated.cs
Add the ability to set the response modality to the GenerateContent call, and a test for Image generation with it.
***
***
***
> [VertexAI] Add response modality to GenerateContent

- vertexai/src/Chat.cs
- vertexai/src/GenerativeModel.cs
- vertexai/testapp/Assets/Firebase/Sample/VertexAI/UIHandlerAutomated.cs
Support providing a CancellationToken to the various GenerateContent calls. Removes the version with params, instead supporting a single input, or a collection of inputs, along with the optional cancellation token.
***
Running the tests locally.
***
***
> [VertexAI] Support cancellation in GenerateContent

- vertexai/src/LiveSession.cs
Remove the closeOnTurnComplete parameter from ReceiveAsync. It should always close after receiving the TurnComplete message, as it is easy enough for the developer to restart it on their end if they want.
***
***
***
> [VertexAI] Remove option from LiveSession Receive

- vertexai/src/Safety.cs
Add new option HarmBlockThreshold Off, which is similar to None, but also sets the response to not include the metadata about the HarmCategory as well.
***
***
***
> [VertexAI] Add HarmBlockThreshold Off

- vertexai/src/GenerativeModel.cs
- vertexai/src/Internal/FirebaseInterops.cs
- vertexai/src/LiveGenerativeModel.cs
Adds the correct version info to the rest request headers. This uses reflection to get the information, since the properties are either internal or private, which prevents easier access.
***
***
***
> [VertexAI] Add version info to the rest calls

- vertexai/src/Schema.cs
- vertexai/testapp/Assets/Firebase/Sample/VertexAI/UIHandlerAutomated.cs
Add Schema support for: Title, MinItems, MaxItems, Minimum, Maximum, PropertyOrdering, AnyOf
***
Added some new test cases
***
***
> [VertexAI] Add new Schema options

- firebaseai/testapp/readme.md
>After the App Store started requiring Xcode 16 in April 2025, Firebase now requires at least 16.2
***
***
- [ x] Other, such as a build process or documentation change.
***
> Update Xcode minimum to 16.2

- .github/workflows/build_android.yml
- .github/workflows/build_ios.yml
- .github/workflows/build_linux.yml
- .github/workflows/build_macos.yml
- .github/workflows/build_starter.yml
- .github/workflows/build_tvos.yml
- .github/workflows/build_windows.yml
- .github/workflows/generate_swig.yml
- .github/workflows/integration_tests.yml
- .github/workflows/package.yml
- README.md
- release_build_files/CMakeLists.txt
- scripts/build_scripts/build_package.py
- scripts/build_scripts/build_zips.py
- scripts/create_debug_export.py
- scripts/gha/integration_testing/build_testapps.json
- scripts/gha/restore_secrets.py
- unity_packer/exports.json
Adds FirebaseAI to the nightly build process by default. Includes adding it to the large packaging process. Also fix the alphabetical ordering for some of the things from the rename from VertexAI.
***
https://github.com/firebase/firebase-unity-sdk/actions/runs/14896247284
***
***
> [FirebaseAI] Add it to the nightly build process

- app/src/swig/app.i
Add FirebaseAI to heartbeat logic, by using reflection in App to determine if FirebaseAI is present, and adding the appropriate user agent.
***
https://github.com/firebase/firebase-unity-sdk/actions/runs/14914214976
***
***
> [FirebaseAI] Add heartbeat info

- firebaseai/CMakeLists.txt
- firebaseai/src/Candidate.cs
- firebaseai/src/Chat.cs
- firebaseai/src/Citation.cs
- firebaseai/src/CountTokensResponse.cs
- firebaseai/src/FirebaseAI.cs
- firebaseai/src/GenerateContentResponse.cs
- firebaseai/src/LiveSessionResponse.cs
- firebaseai/src/ModelContent.cs
- firebaseai/src/ResponseModality.cs
- firebaseai/src/Schema.cs
Change properties to not use lambda notation, since the generated ref docs weren't handling them well. Add comments to ResponseModality enum.
***
Looking at the generated ref docs
***
***
> [FirebaseAI] Fix minor issues with reference docs

- firebaseai/testapp/Assets/Firebase/Sample/FirebaseAI/UIHandler.cs
- firebaseai/testapp/Assets/Firebase/Sample/FirebaseAI/UIHandlerAutomated.cs
Adds some basic logic to send and receive text via both backends as either single messages or an ongoing chat.
***
***
***
> [FirebaseAI] Add basic logic to the sample

- .github/workflows/build_android.yml
- .github/workflows/build_ios.yml
- .github/workflows/build_macos.yml
- .github/workflows/build_tvos.yml
- .github/workflows/integration_tests.yml
- gha/unity/unity_installer.py
- scripts/gha/print_matrix_configuration.py
> Update Mac runners to macos-14 and Xcode to 16.2.

- cmake/build_shared.cmake
- cmake/build_universal.cmake
- docs/readme.md
Set the common-page-size to 16 KB as well. Since we currently use an older NDK version (r21e), this additional flag needs to be set to guarantee that some of the internals are aligned correctly to the new file size. https://developer.android.com/guide/practices/page-sizes#compile-r26-lower
Fixes #1259 
***
Testing locally via emulator
https://github.com/firebase/firebase-unity-sdk/actions/runs/15406475092
***
***
> Set Android common page size to 16 KB

- .github/workflows/build_windows.yml
- cmake/unity_mono.cmake
- scripts/build_scripts/build_zips.py
This is the only place that windows-2019 is hard coded; these machines are going away at the end of June.
***
Succeeded here: https://github.com/firebase/firebase-unity-sdk/actions/runs/15452657745
***
***
> Update Windows runner in build_windows action to windows-latest (from windows-2019)

- analytics/testapp/Assets/Firebase/Sample/Analytics/MainScene.unity
- analytics/testapp/Assets/Firebase/Sample/Analytics/MainSceneAutomated.unity
- analytics/testapp/ProjectSettings/ProjectSettings.asset
- auth/testapp/ProjectSettings/ProjectSettings.asset
- crashlytics/testapp/Assets/Firebase/Sample/Crashlytics/MainSceneAutomated.unity
- crashlytics/testapp/ProjectSettings/ProjectSettings.asset
- database/testapp/ProjectSettings/ProjectSettings.asset
- dynamic_links/testapp/ProjectSettings/ProjectSettings.asset
- functions/testapp/ProjectSettings/ProjectSettings.asset
- scripts/gha/integration_testing/MenuScene/Menu.unity
After updating, the macOS GHA runners have been timing out when building the testapps, related to: https://issuetracker.unity3d.com/issues/unable-to-fall-back-to-cpu-lightmapper-dot-errors-in-the-console-when-opening-a-project-on-a-virtual-machine
Change the testapps to consistently not bake the lightmaps and support metal. Some of them already were.
***
https://github.com/firebase/firebase-unity-sdk/actions/runs/15483427151
***
***
> Fix macOS runner lightmap and metal issues

- docs/readme.md
Update the readme for the upcoming bug fix release.
***
***
***
> Update readme for 12.10.1

- docs/readme.md
- firebaseai/src/GenerateContentResponse.cs
- firebaseai/src/GenerationConfig.cs
- firebaseai/src/Imagen/ImagenConfig.cs
- firebaseai/testapp/Assets/Firebase/Sample/FirebaseAI/UIHandlerAutomated.cs
Add support for defining a thinking budget, and getting a thought token count back as part of the results. Note that only newer models support this feature.
***
Running the tests locally
***
***
> [Firebase AI] Add support for Thinking budget

- firebaseai/testapp/Assets/Firebase/Sample/FirebaseAI/UIHandlerAutomated.cs
Some of the nightly tests are timing out because the youtube summary test is slow, so bump up the timeout.
***
***
***
> [Firebase AI] Increase the test timeout

- docs/readme.md
- firebaseai/src/Candidate.cs
- firebaseai/src/Chat.cs
- firebaseai/src/Citation.cs
- firebaseai/src/CountTokensResponse.cs
- firebaseai/src/GenerateContentResponse.cs
- firebaseai/src/LiveSessionResponse.cs
- firebaseai/src/ModelContent.cs
- firebaseai/src/Schema.cs
Change public field types from ReadOnlyMemory<byte> to just byte[], since that is more inline with was Unity expects. Change IEnumerable to IReadOnlyList where appropriate, to better reflect the underlying data.
***
Running the tests locally
***
***
> [Firebase AI] Change public fields to easier types

- docs/readme.md
- firebaseai/src/FunctionCalling.cs
- firebaseai/src/ModelContent.cs
- firebaseai/testapp/Assets/Firebase/Sample/FirebaseAI/UIHandlerAutomated.cs
- firebaseai/testapp/Assets/StreamingAssets/TestData/vertexai/unary-success-code-execution.json
- firebaseai/testapp/Assets/StreamingAssets/TestData/vertexai/unary-success-code-execution.json.meta
In Firebase AI Logic, add support for enabling Code Execution.
***
Running the tests locally.
***
***
> [Firebase AI] Add support for Code Execution

- gha/unity/unity_installer.py
The GitHub actions started failing to install Unity correctly on Mac, seems the likely problem is it needs to use the arm64 installer, so change it to that.
***
https://github.com/firebase/firebase-unity-sdk/actions/runs/17745007883
https://github.com/firebase/firebase-unity-sdk/actions/runs/17747127860
***
***
> Update the Unity Hub mac installer to arm64

- firebaseai/testapp/Assets/Firebase/Sample/FirebaseAI/UIHandlerAutomated.cs
Format the automated test file. This has no functionality change, just formatting.
***
***
***
> [Firebase AI] Format the automated tests
