.gitignore
cmake/unity_mono.cmake
editor/CMakeLists.txt
editor/analytics/CMakeLists.txt
editor/auth/CMakeLists.txt
editor/crashlytics/CMakeLists.txt
editor/dynamic_links/CMakeLists.txt
editor/messaging/CMakeLists.txt

Build other editor libraries

---

scripts/gha/desktop_tester.py
scripts/gha/gcs_uploader.py
scripts/gha/test_lab.py

Simply migrate test scripts form google3 to github

Add test scripts to open source

---

.gitignore
build_windows_x32.bat
build_windows_x64.bat

- added `.vscode/`
- fixed spelling error for `*_unity_seperate/`

cleanup .gitignore

---

.github/workflows/package.yml
pull_request_template.md
scripts/gha/requirements.txt

Add package workflow for unity sdk

Add package workflow for unity sdk

---

.github/workflows/ios.yml

Have the init workflow setup for ios build
***

initial setup for build ios

---

.github/workflows/package.yml
CMakeLists.txt
build_ios.sh

Add packaging iOS and some minor fix. Still failing on Firestore iOS build to be worked on.
***
***

iOS build fix and package

---

.github/workflows/integration_tests.yml
scripts/gha/print_matrix_configuration.py
scripts/gha/test_lab.py

Add config script and use the script in workflow.
Add scheduled trigger.
Not in this PR:
no config for other workflows except integration test workflow.
some configs are not used for now, but will be used in the future.
auto-diff feature.

Add config script & scheduled trigger

---

.github/workflows/android.yml
.github/workflows/package.yml
CMakeLists.txt
aar_builder/build_aar.py
firestore/CMakeLists.txt
firestore/src/swig/CMakeLists.txt

+ Make android build on linux
+ Add android into package workflow
+ Fix the Firestore build problem on mobile
***
***

Android build on linux

---

CMakeLists.txt
build_package.py
cmake/unity_pack.cmake
editor/app/CMakeLists.txt

Add ability to pack whole folder and update the editor assets
***
GHA test on iOS build and package
***
***

Add ability to pack whole folder and update the editor assets

---

unpack_package.py

Add scripts to unpack unitypackage and generate tree output
***
***

Add scripts to unpack unitypackage and generate tree output

---

.github/workflows/package.yml
CMakeLists.txt
build_package.py
external/CMakeLists.txt
release_build_files/CMakeLists.txt
unpack_package.py

fix some misc build missing files and add ability to package tgz
***
locally build and packaged
***
***

fix some misc build missing files and add ability to package tgz

---

.github/workflows/package.yml
.github/workflows/sdk_build.yml
cmake/build_shared.cmake
cmake/firebase_unity_version.cmake
cmake/unity_pack.cmake
firestore/src/swig/CMakeLists.txt
remote_config/CMakeLists.txt
scripts/gha/print_matrix_configuration.py

shared cpp library for each product is now packed
linux version set to updated ([linux versions](https://public-cdn.cloud.unity3d.com/hub/prod/releases-linux.json))
Add remote config missing c# file
***
Test locally and GHA build
***
***

Multiple Build fix

---

analytics/testapp/Assets/Plugins/Android/AndroidManifest.xml.meta
analytics/testapp/Assets/Plugins/Android/project.properties.meta
analytics/testapp/ProjectSettings/PackageManagerSettings.asset
analytics/testapp/ProjectSettings/PresetManager.asset
analytics/testapp/ProjectSettings/ProjectVersion.txt
analytics/testapp/ProjectSettings/VFXManager.asset
analytics/testapp/ProjectSettings/XRSettings.asset

Upgrade analytics testapp
***
N/A
***
***

Upgrade analytics testapp

---

.github/workflows/integration_tests.yml

1 line fix. set build OS correctly
***
***

[Bugfix] set build OS correctly

---

.github/workflows/integration_tests.yml
scripts/gha/print_matrix_configuration.py

Fix nightly integration test CI not setting test matrix correctly.
***
https://github.com/firebase/firebase-unity-sdk/actions/runs/1536473178
***
***

Fix nightly integration test matrix 

---

.github/workflows/update_versions.yml

Create the workflow first
***
***

init workflow

---

.github/workflows/android.yml
.github/workflows/ios.yml
.github/workflows/package.yml
.github/workflows/sdk_build.yml
.github/workflows/update_versions.yml
build_package.py
cmake/firebase_unity_version.cmake
scripts/gha/create_pull_request.py
scripts/gha/print_matrix_configuration.py
scripts/gha/requirements.txt
scripts/update_versions.py

Able to update versions with input
***
in GHA and locally
***
***

Create update_version workflow

---

cmake/firebase_unity_version.cmake
unity_packer/exports.json

Bump up EDM4U version to 1.2.168
***
N/A
***
***

Bump up EDM4U version to 1.2.168

---

scripts/gha/build_testapps.py
scripts/gha/print_matrix_configuration.py

Integration Test CI enables windows OS building Android Testapps

---

scripts/gha/print_matrix_configuration.py

Unity update linux 2019 version again

---

app/src/cpp_instance_manager.h
app/src/swig/app.i
auth/src/swig/auth.i
crashlytics/src/cpp/android/crashlytics_android.h
crashlytics/src/cpp/common/crashlytics.cc
crashlytics/src/cpp/stub/crashlytics_stub.h
database/src/swig/listener.i
messaging/src/swig/messaging.i
storage/src/swig/monitor_controller.h

Fix build error caused by CPP SDK change

---

.github/workflows/sdk_build.yml
scripts/gha/print_matrix_configuration.py

> Add a reference for cpp sdk checkout
> Update Linux 2020 Unity version again. (We would need to detect automatically since Unity keep changing available versions)
***
> https://github.com/firebase/firebase-unity-sdk/actions/runs/1684128556
***
***

Some tiny tweak for the release process

---

.github/workflows/package.yml

Add SHA for SDK output zip

---

.github/workflows/integration_tests.yml
.github/workflows/ios.yml
.github/workflows/package.yml
build_package.py
unpack_package.py

Fix the issue that no EDM4U is packaged

---

build_package.py
cmake/build_shared.cmake

build package fix

---

.github/workflows/integration_tests.yml
scripts/gha/build_testapps.py
scripts/gha/integration_testing/test_validation.py
scripts/gha/it_workflow.py
scripts/gha/requirements.txt

1. Added label_trigger & postsubmit_trigger for Integration Test CI
2. Added github action related scripts.
3. Generated build & test log for Summary Report
Related logs & artifacts are generated :
https://github.com/firebase/firebase-unity-sdk/actions/runs/1714106097
***

Preparation for Integration Test Summary Report

---

.github/workflows/integration_tests.yml
scripts/gha/build_testapps.py
scripts/gha/integration_testing/test_validation.py
scripts/gha/it_workflow.py
scripts/gha/print_matrix_configuration.py
scripts/gha/requirements.txt
scripts/gha/summarize_test_results.py

Generate Integration Test Summary Report
See comment section.
***

Generate Integration Test Summary Report

---

cmake/firebase_unity_version.cmake
unity_packer/exports.json

Roll-up EDM4U version to 1.2.169
***
N/A
***
***

Roll-up EDM4U version to 1.2.169

---

.github/workflows/integration_tests.yml
scripts/gha/build_testapps.py
scripts/gha/integration_testing/automated_testapp/AutomatedTestRunner.cs
scripts/gha/print_matrix_configuration.py
scripts/gha/unity_installer.py

1. Updated firebase Unity SDK 
2. Updated firestore test code 
3. Modified & Enabled firestore test in CI
***
See comment below. 
Firestore tests all passed, thus not present in the report.
***
***

Update firestore code & enable firestore test in CI

---

.github/workflows/android.yml
.github/workflows/ios.yml
.github/workflows/sdk_build.yml
CMakeLists.txt
analytics/CMakeLists.txt
app/CMakeLists.txt
app/src/swig/future.i
app/src/swig/serial_dispose.i
auth/CMakeLists.txt
cmake/build_shared.cmake
cmake/build_universal.cmake
cmake/ios_pack.cmake
cmake/unity_pack.cmake
crashlytics/CMakeLists.txt
database/CMakeLists.txt
dynamic_links/CMakeLists.txt
firestore/CMakeLists.txt
functions/CMakeLists.txt
installations/CMakeLists.txt
messaging/CMakeLists.txt
remote_config/CMakeLists.txt
scripts/gha/print_matrix_configuration.py
storage/CMakeLists.txt

Fixing iOS packing issues

---

.github/workflows/integration_tests.yml
scripts/gha/build_testapps.py
scripts/gha/print_matrix_configuration.py
scripts/gha/summarize_test_results.py
scripts/gha/test_lab.py
scripts/gha/test_simulator.py

1. For expanded matrix: added Windows Build OS, Unity Version 2017, Android/iOS platforms by default.
2. To save Windows disk space, delete intermediate files afterwords; `move` instead of `copy` artifacts. 
3. Refactored the mobile test matrix, now mobile test can run on different mobile devices.
4. Synced the `test_lab.py`, `test_simulator.py` with CPP repo. (catch errors, retry on erros)
NOT include: 
1. fix storage testapp failures
2. fix Android Emulator failures
See the comment below
***

Fix & Enable full expanded matrix in Integration Test CI

---

CMakeLists.txt
README.md
build_android.sh
build_package.py
cmake/android_dependencies.cmake
cmake/firebase_unity_version.cmake
firestore/CMakeLists.txt
scripts/update_versions.py

Fix android dependency related logic

---

.github/workflows/sdk_build.yml
CMakeLists.txt
build_windows_x64.bat
scripts/gha/print_matrix_configuration.py

github environment fix

---

CMakeLists.txt

disable the fexceptions which cause windows build error

---

.github/workflows/android.yml
aar_builder/merge_aar.sh
build_android.sh

Adds logic to build multi-architecture Android libraries
***
Running locally, and running the Github workflow
***
***

Logic to build multi-architecture Android libraries

---

build_ios.sh

make iOS build fat lib

---

scripts/gha/print_matrix_configuration.py

Enable all Testapps & all Platform in Integration Test CI
Out of the scope: fix the failed testapps.
***
See comment below
***
***

Enable all Testapps & all Platform in Integration Test CI

---

.github/workflows/integration_tests.yml
scripts/gha/print_matrix_configuration.py

Disable test on Android Emulator temporarily.
***
See the comment below.
***
***

Disable test on Android Emulator temporarily

---

.github/workflows/package.yml

Add all tgz sha hash into the doc
***
***
***

Prepare sha for tgz 

---

.github/workflows/android.yml

The bash script is having problems on the GitHub runners, so changing it to the new python script
***
***
***

Change Android workflow to use the python script

---

build_android.sh

Fix the build_android bash script to convert the find results into an array correctly
***
***
***

Fix the build_android bash script

---

.github/workflows/sdk_build.yml
scripts/build_scripts/build_zips.py

turn off boringssl on linux and windows

---

.github/workflows/android.yml
.github/workflows/integration_tests.yml
.github/workflows/ios.yml
.github/workflows/sdk_build.yml

It seems the newer version of u3d also has a problem on Linux. Pin to the old version, and also disable checking for new versions, since that check also causes errors.
***
***
***

Pin to an old version of u3d

---

docs/readme.md

Update the readme for the upcoming release, which will be 9.1.0.  The other version numbers were already updated in a previous PR.
***
***
***

Update readme for 9.1.0 release

---

.github/workflows/build_linux.yml
scripts/gha/unity_installer.py

Fix Unity version on linux runner

---

cmake/firebase_unity_version.cmake
unity_packer/exports.json

Roll up EDM4U deps to `1.2.172`
***
N/A
***
***

Rollup EDM4U deps to 1.2.172

---

scripts/gha/it_workflow.py

The format of Nightly Test Report on Unity repo is different from C++ repo.
Fixed the format.
***
Current Report:
https://github.com/firebase/firebase-unity-sdk/issues/157
***
***

Fix "Nightly Integration Testing Report"

---

docs/readme.md

Copies the change notes from c++ 9.3.0 release notes
***
n/a
***
- [x ] Other, such as a build process or documentation change.
***

Copy 9.3.0 change notes from C++ 9.3.0 change notes

---

.github/workflows/build_linux.yml
analytics/CMakeLists.txt
app/CMakeLists.txt
auth/CMakeLists.txt
auth/src/PhoneAuthProvider.cs
cmake/firebase_swig.cmake
cmake/unity_pack.cmake
crashlytics/CMakeLists.txt
database/CMakeLists.txt
dynamic_links/CMakeLists.txt
firestore/CMakeLists.txt
functions/CMakeLists.txt
installations/CMakeLists.txt
messaging/CMakeLists.txt
remote_config/CMakeLists.txt
scripts/build_scripts/build_zips.py
storage/CMakeLists.txt

Add logic to generate a zip file that contains the C# files that have doxygen style comments, that can then be used to generate the reference docs.
***
Running and testing locally
***
***

Add logic to generate source file zip needed for documentation

---

.github/workflows/build_android.yml
.github/workflows/build_ios.yml
.github/workflows/build_linux.yml
.github/workflows/build_macos.yml
.github/workflows/build_windows.yml
.github/workflows/package.yml

make sub workflows more visible

---

.github/workflows/build_linux.yml
.github/workflows/package.yml
scripts/build_scripts/build_package.py

Add logic to the linux workflow (since it is generally the fastest already) to generate the zip file containing the sources to document. Also updates the packaging logic to ignore it.
***
https://github.com/firebase/firebase-unity-sdk/actions/runs/2742344076
***
***

Add logic to the workflow to build the docs zip

---

docs/readme.md

Add a space between comma separated list of words
***
N/A
***
- [ x] Other, such as a build process or documentation change.
***

Minor formatting fix to release notes

---

docs/readme.md

Update release notes for version 9.4.0.
***
None. This is only a change to the release notes.
***
***

Update release notes for v9.4.0 release.

---

scripts/gha/it_workflow.py

Also, updated current issue name.
***
***
***

Add [Unity] description to the nightly test report

---

docs/readme.md

Update readme.md for Unity 9.6.0 release
***
N/A
***
***

Update readme.md for `9.6.0` release

---

cmake/firebase_unity_version.cmake
unity_packer/exports.json

Roll up EDM4U deps to `1.2.173`
***
N/A
***
***

Rollup EDM4U deps to 1.2.173

---

cmake/firebase_unity_version.cmake
unity_packer/exports.json

Roll up EDM4U dependencies to `1.2.174`
***
[Unity Build CI](https://github.com/firebase/firebase-unity-sdk/actions/runs/3221153763)
***
***

Rollup EDM4U dependencies to 1.2.174

---

docs/readme.md

Update release readme info

---

LICENSE

Add MiniJSON to the license disclosure.
***
N/A
***
***

Add MiniJSON to license file

---

.github/workflows/integration_tests.yml
scripts/gha/build_testapps.py

The Android SDK has a couple of different paths the sdkmanager could be, so attempt those when searching for it.
***
https://github.com/firebase/firebase-unity-sdk/actions/runs/3317150614
***
***

Fix Android integration testapp build

---

.github/workflows/integration_tests.yml
scripts/gha/print_matrix_configuration.py

1. Upgrade FTL GHA (solve `set-output` issue)
2. fix issue of pending jobs: "Error parsing fromJson,.github/workflows/integration_tests.yml (Line: 503, Col: 15): Error parsing NaN value."
***
Playmode only (only playmode job triggered): https://github.com/firebase/firebase-unity-sdk/actions/runs/3317762747
Android Platform only (will skip playmode job): https://github.com/firebase/firebase-unity-sdk/actions/runs/3317763552
'a' Platform (none of the build & test jobs will be triggered): https://github.com/firebase/firebase-unity-sdk/actions/runs/3317784723
Also see the full test result in the comment.
***
***

Update FTL GHA version & other minor fixes

---

docs/readme.md

Adds version numbers for the dependencies. Uses the same phrasing as the C++ release notes for easier copy pasting.
***
N/A
***
***

Update release notes for 10.1.0 release

---

.github/workflows/build_starter.yml
.github/workflows/integration_tests.yml
.github/workflows/package.yml
.github/workflows/update_versions.yml

Update workflow to reduce spam

---

docs/readme.md

Update to the release notes for release v10.1.1.
***
N/A
***
***

10.1.1 release notes

---

README.md

Some hyphens got replaced by special character hyphens, which cause errors when copied into a command line. Replace with the correct version.
***
***
***

Fix incorrect hyphens in the top level readme

---

cmake/firebase_unity_version.cmake
gha/unity/unity_installer.py
unity_packer/exports.json

Update EDM4U to its latest release, v1.2.175
***
[Unity Build](https://github.com/firebase/firebase-unity-sdk/actions/runs/3497216763) -> [Integration Test CI](https://github.com/firebase/firebase-unity-sdk/actions/runs/3497871405)
***
***

Update EDM4U dependency to 1.2.175

---

docs/readme.md

Update the release notes for the upcoming v10.2.0 release.
Release notes reflect the update in the iOS and Android dependencies.
***
N/A
***
***

Update Release Notes for v10.2.0

---

.github/workflows/generate_swig.yml

Adding a new workflow that can be used to generate the swig code.
***
None yet, needs to be submitted first.
***
***

Initial generate swig workflow

---

docs/readme.md

Update the readme for the upcoming 10.3.0 release
***
***
***

Update readme for 10.3.0 release

---

.allstar/binary_artifacts.yaml

Except from go/allstar check (#575) because those files are either for build or for the onboarding tools.
***
N/A
***
***

Exempt from go/allstar check

---

README.md

Update the top level readme.
***
***
***

Call out that desktop is for development purposes

---

docs/readme.md

Update release notes for upcoming release

[Crashlytics ODF] update release notes

---

app/src/AppOptions.cs
app/src/ErrorMessages.cs
app/src/swig/app.i
app/src/swig/future.i
auth/src/PhoneAuthProvider.cs
auth/src/swig/auth.i
crashlytics/src/IOSImpl.cs
crashlytics/src/Metadata.cs
crashlytics/testapp/Assets/Firebase/Sample/Crashlytics/UIHandler.cs
database/src/Query.cs
docs/readme.md
firestore/src/swig/firestore.i
installations/src/swig/installations.i
messaging/src/swig/messaging.i

Update the reference docs to refer to tvOS when discussing particular methods and classes.
***
[Unity Packaged Build for docs staging.](https://github.com/firebase/firebase-unity-sdk/actions/runs/3751047334)
***
***

tvOS Reference Doc Changes

---

docs/readme.md

Update release note in readme.md for upcoming release
***
N/A
***
***

Update release note in readme.md for 10.5.0

---

crashlytics/src/cpp/common/crashlytics.cc

A recent change on the C++ side added another parameter to the CALLBACK macro, so update crashlytics to it.
***
***
***

Update crashlytics with C++ callback change

---

.gitignore
scripts/build_scripts/build_package.py

Update `.gitignore` to ignore downloaded ndk and EDM4U
Also update packaging script to check if EDM4U is downloaded to `*_unity` folder.
***
N/A
***
***

Update .gitignore and patch packaging script

---

app/src/swig/app.i

Make sure the user-agents are registered before C++ App is created.
Depends on a new utility function introduced in https://github.com/firebase/firebase-cpp-sdk/pull/1217
***
E2E test using Auth iOS/Android testapp
***
***

Fix user-agent register timing in Unity SDK

---

docs/readme.md

update readme for new release

---

firestore/scripts/cp_unity_testapp.py

Remove Unity 2017 support from `cp_unity_testapp.py`, simplifying its command-line arguments. Previously, you would need to specify one, or both, of `--dest_dir_2017` and `--dest_dir_2020`. Now, you only need to specify the destination directory as a positional argument.
Also, the concept of a "defaults file" for the script was removed. This feature was rarely (ever?) used and added confusion to the code and the command-line interface.

firestore: cp_unity_testapp.py: remove unity 2017 support

---

docs/readme.md

Update release notes for 10.7.0 release
***
N/A
***
***

Update release notes for 10.7.0

---

app_check/src/AppCheckToken.cs
app_check/src/FirebaseAppCheck.cs
app_check/src/swig/app_check.i

Adds logic for GetAppCheckTokenAsync, to call into the C++ SDK, and also logic for the C++ SDK to call up to the Factory and Provider set in Unity.
Adds TokenChanged event, that gets callbacks when the App Check token is changed.
***
Testing localling
***
***

Add implementation for FirebaseAppCheck class

---

unity_packer/exports.json

Bump up min Unity version metadata for UPM packages.
***
N/A
***
***

Bump up min Unity version for UPM packages

---

auth/src/swig/auth.i

Since C++ API changed to return `User` as a value, C# API will always  created one object pointing to different CPtr while they are all referencing the same user. 
This change added `Firebase.IsValid` and also use comparison operator when updating `FirebaseAuth.currentUser`.
***
GHA
***
***

Fix `FirebaseAuth.CurrentUser`

---

auth/src/swig/auth.i
docs/readme.md

Auth Google I/O release note update
***
N/A
***
***

Auth Google I/O release note update

---

auth/src/swig/auth.i

Make this consistent to `Credential.IsValid()`
Make it consistent with `Credential.IsValid()`
***
GHA
***
***

Change `FirebaseUser.IsValid()` to a method

---

auth/testapp/Assets/Firebase/Sample/Auth/UIHandler.cs
auth/testapp/Assets/Firebase/Sample/Auth/UIHandlerAutomated.cs
firestore/testapp/Assets/Firebase/Sample/Firestore/UIHandlerAutomated.cs
firestore/testapp/Assets/Tests/FirestoreInstanceTests.cs
functions/testapp/Assets/Firebase/Sample/Functions/UIHandlerAutomated.cs

Add Auth Integration tests for new APIs
***
GHA
Auth only: https://github.com/firebase/firebase-unity-sdk/actions/runs/4898581406
Auth/Firestore/Functions: https://github.com/firebase/firebase-unity-sdk/actions/runs/4898601347
***
***

Add Auth Integration tests for new APIs

---

docs/readme.md

Update release note for 11.0.1
***
N/A
***
***

Update release note for 11.0.1

---

app_check/testapp/Assets/Firebase/Sample/AppCheck/UIHandler.cs
app_check/testapp/Assets/Firebase/Sample/AppCheck/UIHandlerAutomated.cs
app_check/testapp/readme.md
scripts/gha/restore_secrets.py

Add some basic logic to the App Check testapps, and some minor tests to the automated one.
***
https://github.com/firebase/firebase-unity-sdk/actions/runs/4986400307
***
***

Add more use cases to the App Check testapps

---

.github/workflows/build-report.yml

add report workflow for init

---

scripts/gha/create_pull_request.py
scripts/gha/firebase_github.py
scripts/gha/it_workflow.py
scripts/gha/trigger_workflow.py

rename github.py to firebase_github.py

---

scripts/gha/test_simulator.py

The xcodes install can fail when not run as root, so do so.
Same as https://github.com/firebase/firebase-cpp-sdk/pull/1379
***
***
***

Run simulator install as root

---

auth/src/swig/auth.i

firebase::SharedPtr was removed in the C++ SDK, so switch over to std::shared_ptr.
***
***
***

Switch SharedPtr to std::shared_ptr.

---

firestore/src/swig/map.h

This include file was removed from the C++ SDK.
***
***
***

Remove bad include.

---

.github/workflows/build_tvos.yml

tvOS build is failing because it can't remove the pod cache for some reason. Adding this clear earlier in the build fixes it.
***
***
***

Clear Cocoapods cache before adding pod repo.

---

installations/testapp/Assets/Firebase/Sample/Installations/UIHandlerAutomated.cs

The Installations Race Condition test can throw a null exception at one point, and I think that is somewhat expected, so handle that.  Failure seen in https://github.com/firebase/firebase-unity-sdk/actions/runs/5540889753/jobs/10116203622
***
***
***

Adjust Installations Race Condition test

---

analytics/testapp/Assets/Firebase/Sample/Analytics/UIHandlerAutomated.cs

The previous PR messed up on the if definition, so fix it.
***
***
***

Fix Analytics on iOS CI issue

---

analytics/testapp/Assets/Firebase/Sample/Analytics/UIHandlerAutomated.cs

Messed up the parenthesis on the previous PR
***
***
***

Add missing parenthesis

---

docs/readme.md

m134 readme update

---

scripts/gha/it_workflow.py

Python script was complaining about an undefined variable, so define it.
***
***
***

Fix missing variable definition in it_workflow

---

scripts/gha/print_matrix_configuration.py

Update the iOS version used by FTL, since the old version was removed.
Version determined by following these instructions: https://firebase.google.com/docs/test-lab/ios/available-testing-devices
***
***
***

Update the iOS version used by FTL

---

analytics/testapp/Assets/Firebase/Sample/Analytics/UIHandler.cs
docs/readme.md

The C++ SDK is adding a new Analytics function for phone number conversion, which will automatically be added to the Unity SDK due to swig.  https://github.com/firebase/firebase-cpp-sdk/pull/1429
This adds it to the test, and the readme.
***
***
***

Add test for new Analytics conversion feature

---

scripts/gha/report_build_status.py

Split the Firestore tests into its own column in the nightly reports, so that it is easier to tell at a glance the state of everything.
***
Running the script locally.
***
***

Split nightly Firestore tests into its own column

---

editor/crashlytics/src/iOSPostBuild.cs

related change: https://github.com/firebase/firebase-ios-sdk/pull/11867

Update script upload symbol path

---

cmake/android_dependencies.cmake

The Android dependencies were not meant to be part of this update.
***
***
***

Undo Android update

---

firestore/src/swig/CMakeLists.txt

The Firestore iOS dependency changed the directory layout, so update the CMake logic accordingly.
***
https://github.com/firebase/firebase-unity-sdk/actions/runs/6791564195
***
***

Update Firestore headers directory

---

.github/workflows/integration_tests.yml
scripts/gha/it_workflow.py

Per recommendations in https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
***
***
***

Change substitution to occur via environment variables.

---

.github/workflows/retry-test-failures.yml

Add placeholder so that the workflow will be present in the workflow_dispatch list.
***
***
***

Add placeholder workflow for retrying test failures.

---

.github/workflows/build-report.yml
.github/workflows/build_android.yml
.github/workflows/build_ios.yml
.github/workflows/build_linux.yml
.github/workflows/build_macos.yml
.github/workflows/build_starter.yml
.github/workflows/build_tvos.yml
.github/workflows/build_windows.yml
.github/workflows/generate_swig.yml
.github/workflows/integration_tests.yml
.github/workflows/package.yml
.github/workflows/update_versions.yml
cmake/android_dependencies.cmake
cmake/firebase_unity_version.cmake
docs/readme.md
scripts/gha/build_testapps.py

Update to the latest C++ SDK, and the equivalent Android/iOS dependencies.  Update the versions of python and Node used by the GHA runners, because the CLI needs it.  Increase the timeout range on the macOS build, since the build seems to be taking longer because of dependency changes.
***
Runs on another branch with these changes
***
***

Update dependencies to latest, and other fixes

---

.github/workflows/integration_tests.yml

Update the Firebase testlab version used to 1.4
***
***
***

Update the Firebase testlab version used

---

scripts/gha/print_matrix_configuration.py

The FTL device model dreamlte has been timing out on running tests, due to out of date play services, so remove it from the list. A similar change was done on the C++ repo.
***
***
***

Remove out of date device from test matrix

---

scripts/gha/print_matrix_configuration.py

Remove ipadmini4 from the set of devices to test against, since it is no longer available on FTL
***
***
***

Remove invalid iOS device from test list

---

scripts/gha/print_matrix_configuration.py

Already removed from the test build matrix, needs to be removed from the test test matrix.
***
***
***

Remove Mac Android from the test matrix

---

app_check/testapp/readme.md
unity_packer/debug_single_export_json/analytics.json
unity_packer/debug_single_export_json/app_check.json
unity_packer/debug_single_export_json/auth.json
unity_packer/debug_single_export_json/crashlytics.json
unity_packer/debug_single_export_json/database.json
unity_packer/debug_single_export_json/dynamic_links.json
unity_packer/debug_single_export_json/firestore.json
unity_packer/debug_single_export_json/functions.json
unity_packer/debug_single_export_json/installations.json
unity_packer/debug_single_export_json/messaging.json
unity_packer/debug_single_export_json/remote_config.json
unity_packer/debug_single_export_json/storage.json
unity_packer/exports.json

Update some more minimum versions from Unity 2019 to 2020, mostly around the packages
***
***
***

Update some minimum versions that were missed

---

scripts/gha/print_matrix_configuration.py

Fix parameter name in the test matrix configuration script
***
***
***

Fix error in test matrix configuration

---

scripts/gha/print_matrix_configuration.py

Update the iOS simulator versions to the same that C++ now uses, from https://github.com/firebase/firebase-cpp-sdk/pull/1592
***
***
***

Update iOS simulator devices for testing

---

scripts/gha/print_matrix_configuration.py

The C++ and Unity scripts are formatted slightly differently, which caused a problem when updating the version numbers.  Fix the formatting.
***
***
***

Fix the print_matrix script

---

.github/workflows/integration_tests.yml
scripts/gha/report_build_status.py

Now logs the Run ID explicitly in the summarize step.
***
***
***

Fix reporting of retried jobs.

---

analytics/testapp/ProjectSettings/ProjectSettings.asset
app_check/testapp/ProjectSettings/ProjectSettings.asset
auth/testapp/ProjectSettings/ProjectSettings.asset
crashlytics/testapp/ProjectSettings/ProjectSettings.asset
database/testapp/ProjectSettings/ProjectSettings.asset
dynamic_links/testapp/ProjectSettings/ProjectSettings.asset
firestore/testapp/ProjectSettings/ProjectSettings.asset
functions/testapp/ProjectSettings/ProjectSettings.asset
installations/testapp/ProjectSettings/ProjectSettings.asset
messaging/testapp/ProjectSettings/ProjectSettings.asset
remote_config/testapp/ProjectSettings/ProjectSettings.asset
storage/testapp/ProjectSettings/ProjectSettings.asset

Update the target tvOS versions in the testapps.
***
***
***

Update testapp tvOS versions

---

scripts/update_versions.py
unity_packer/debug_single_export_json/analytics.json
unity_packer/debug_single_export_json/app_check.json
unity_packer/debug_single_export_json/auth.json
unity_packer/debug_single_export_json/crashlytics.json
unity_packer/debug_single_export_json/database.json
unity_packer/debug_single_export_json/dynamic_links.json
unity_packer/debug_single_export_json/firestore.json
unity_packer/debug_single_export_json/functions.json
unity_packer/debug_single_export_json/installations.json
unity_packer/debug_single_export_json/messaging.json
unity_packer/debug_single_export_json/remote_config.json
unity_packer/debug_single_export_json/storage.json
unity_packer/exports.json

Add logic to the update script to automatically update the various export json files with the latest EDM4U version.  Also update those files.
***
***
***

Add logic to auto-update export json files

---

firestore/testapp/Assets/Firebase/Sample/Firestore/UIHandlerAutomated.cs

Fix the Firestore test involving Android, since the underlying bug it was working around has now been fixed.
***
***
***

Fix Firestore Android test

---

.github/workflows/integration_tests.yml
.github/workflows/package.yml

This reverts commit cc801087b2098ed66d21f046960d027b728bb501.
***
***
***

Revert "Bump actions/download-artifact from 3 to 4.1.7 (#1102)"

---

unity_packer/debug_single_export_json/analytics.json
unity_packer/debug_single_export_json/app_check.json
unity_packer/debug_single_export_json/auth.json
unity_packer/debug_single_export_json/crashlytics.json
unity_packer/debug_single_export_json/database.json
unity_packer/debug_single_export_json/dynamic_links.json
unity_packer/debug_single_export_json/firestore.json
unity_packer/debug_single_export_json/functions.json
unity_packer/debug_single_export_json/installations.json
unity_packer/debug_single_export_json/messaging.json
unity_packer/debug_single_export_json/remote_config.json
unity_packer/debug_single_export_json/storage.json
unity_packer/exports.json

Update packaging logic to use EDM4U 1.2.183
***
***
***

Update package EDM4U version to 1.2.183

---

scripts/gha/it_workflow.py

The issue constantly being opened and closed is noisy, so just leave it open.
***
***
***

Stop closing the nightly report issue

---

.github/workflows/build_linux.yml
.github/workflows/build_starter.yml
.github/workflows/integration_tests.yml
.github/workflows/package.yml
.github/workflows/update_versions.yml
scripts/gha/print_matrix_configuration.py

Some of the workflows were using ubuntu-latest, which has changed from 20 to 22.  Pin all the workflows to 20, until we want to update all of them to 22 (and solve the issues that come with that).
***
https://github.com/firebase/firebase-unity-sdk/actions/runs/12658363813
***
***

Pin the GitHub Linux machines to 20.04

---

.github/workflows/build_starter.yml

Reduce the automatic build triggers when PRs are submitted. We test nightly already, and generally before the PR is submitted.
***
***
***

Stop triggering builds on PR closed

---

unity_packer/exports.json

The package process is making an empty unity package because of this, so remove it for now.
***
***
***

Remove VertexAI from the package list for now

---

vertexai/src/Candidate.cs
vertexai/src/GenerateContentResponse.cs
vertexai/src/GenerativeModel.cs
vertexai/src/ModelContent.cs
vertexai/src/RequestOptions.cs
vertexai/src/VertexAI.cs

Add the logic needed to do a basic call, with text input and output to the model. Implements the top level class, model, content, and candidate, and the request options.
***
***
***

VertexAI - Add logic for text input/output

---

vertexai/src/GenerativeModel.cs
vertexai/testapp/Assets/Firebase/Sample/VertexAI/UIHandlerAutomated.cs

Add the logic for Streaming a response. Add tests for setting the various options, multiple candidates, and streaming.
***
https://github.com/firebase/firebase-unity-sdk/actions/runs/13579798146
https://github.com/firebase/firebase-unity-sdk/actions/runs/13580286421
***
***

VertexAI - Add Streaming responses, and some tests

---

.github/workflows/package.yml
.github/workflows/update_versions.yml

Workflows that commit changes started breaking because of some permissions change. Add the required permissions to workflows that commit.
***
***
***

Add write permissions for workflows that commit

---

vertexai/src/Chat.cs
vertexai/src/GenerativeModel.cs
vertexai/testapp/Assets/Firebase/Sample/VertexAI/UIHandlerAutomated.cs

Add the implementation of Chat, and some tests for it.
***
Running the tests locally.
***
***

VertexAI - Implement Chat

---

vertexai/src/Chat.cs
vertexai/src/GenerativeModel.cs
vertexai/src/Internal/InternalHelpers.cs
vertexai/src/ModelContent.cs

SystemInstructions should have a role "system", and other clean up / null handling logic.
***
Running tests locally.
***
***

VertexAI - Make SystemInstructions set a role

---

vertexai/src/CountTokensResponse.cs
vertexai/src/GenerateContentResponse.cs
vertexai/src/GenerativeModel.cs
vertexai/src/ModalityTokenCount.cs
vertexai/src/ModalityTokenCount.cs.meta
vertexai/src/VertexAIException.cs
vertexai/testapp/Assets/Firebase/Sample/VertexAI/UIHandlerAutomated.cs

Add the logic for CountTokensAsync, and add the logic to parse ModalityTokenCount in the UsageMetadata.
***
Running locally, adding some new tests.
***
***

VertexAI - Add CountTokens and ModalityTokenCount

---

.github/workflows/integration_tests.yml

The tests seem to be timing out at night, so increase the timeout
***
***
***

Increase the timeout for FTL tests

---

vertexai/src/GenerativeModel.cs
vertexai/src/Internal/EnumConverters.cs
vertexai/src/Internal/EnumConverters.cs.meta
vertexai/src/LiveContentResponse.cs
vertexai/src/LiveContentResponse.cs.meta
vertexai/src/LiveGenerationConfig.cs
vertexai/src/LiveGenerationConfig.cs.meta
vertexai/src/LiveGenerativeModel.cs
vertexai/src/LiveGenerativeModel.cs.meta
vertexai/src/LiveSession.cs
vertexai/src/LiveSession.cs.meta
vertexai/src/ModelContent.cs
vertexai/src/ResponseModality.cs
vertexai/src/ResponseModality.cs.meta
vertexai/src/VertexAI.cs

Adds basic support for BiDirectional streaming support for VertexAI. Note that the feature is experimental still, and very likely to change.
***
Running locally.
***
***

[VertexAI] Add initial support for BiDi streaming

---

vertexai/src/Candidate.cs
vertexai/src/Citation.cs
vertexai/src/FirebaseAI.cs
vertexai/src/FirebaseAI.cs.meta
vertexai/src/GenerateContentResponse.cs
vertexai/src/GenerativeModel.cs
vertexai/src/LiveGenerativeModel.cs
vertexai/src/ModelContent.cs
vertexai/src/Safety.cs
vertexai/testapp/Assets/Firebase/Sample/VertexAI/UIHandlerAutomated.cs

Add support for selecting either the VertexAI or developer API (GoogleAI) backends. Changes the VertexAI class to FirebaseAI.
***
***
***

[VertexAI] Add support for Developer API

---

vertexai/src/Internal/FirebaseInterops.cs
vertexai/src/ModelContent.cs
vertexai/testapp/Assets/Firebase/Sample/VertexAI/UIHandlerAutomated.cs

Add support for including the Auth Token to the backend calls. Also, fix a bug with providing fileData as input. Add a handful of tests for both.
***
Running the tests locally.
***
***

[VertexAI] Add Auth support. Fix fileData input

---

firebaseai/src/GenerativeModel.cs
firebaseai/src/LiveGenerativeModel.cs

Change the request header from genai-csharp to gl-csharp, to better match the other platforms.
***
***
***

[FirebaseAI] Change request header to match other platforms

---

firebaseai/src/ModelContent.cs

Sometimes the model can return an unknown part, so we want to handle that more gracefully than throwing an exception.
***
Running locally.
***
***

[FirebaseAI] Handle unknown parts

---

cmake/firebase_unity_version.cmake

Update the pinned version of the Firebase C++ SDK to the tag for the next Unity release
***
***
***

Update Cpp version pin

---

docs/readme.md
firebaseai/src/CountTokensResponse.cs
firebaseai/testapp/Assets/Firebase/Sample/FirebaseAI/UIHandlerAutomated.cs

Deprecate TotalBillableCharacters, in favor of TotalTokens
***
***
***

[Firebase AI] Deprecate TotalBillableCharacters

---

scripts/update_versions.py

The underlying bug that was blocking Android dependency updates seems to be fixed, so uncomment out the code.
***
***
***

Re-enable Android dependency updates

---

firebaseai/src/Imagen/ImagenModel.cs

Setting includeSafetyAttributes to true for Imagen generation calls. Note that the attributes are not exposed as the response, this is purely for AI monitoring to track the information.
***
***
***

[Firebase AI] Turn on safety attributes for Imagen

---

firebaseai/src/ModelContent.cs
firebaseai/testapp/Assets/Firebase/Sample/FirebaseAI/UIHandlerAutomated.cs

Handle if the backend sends a response with no parts in it, which can happen in some edge cases. Also, slightly reword a test to be more reliable.
***
Running locally.
***
***

[Firebase AI] Handle a response with no Parts
